<?php

$home_path = explode('app/', $_SERVER['SCRIPT_FILENAME'])[0];
require($home_path . '/wp/wp-load.php');

      // add this file to _src/scripts folder (may have to create it)
      // copy/paste the class-clwp.php $logos array below in $logos_array
      // Go to http://localhost:1337/app/themes/coolwhip-child/scripts/logos_alpha_sorted.php to copy/paste the alphabetized array

$logos_array = [
      'a-to-z-valley-wide-movers' => ['name' => 'A to Z Valley Wide Movers', 'source' => 'local', 'image_name' => 'atozvalleywidemovers.png'],
      'b-line-movers' => ['name' => 'B Line Movers', 'source' => 'local', 'image_name' => 'blinemovers.png'],
      'excel-payroll' => ['name' => 'Excel Payroll', 'source' => 'local', 'image_name' => 'excellpayroll.png'],
      'little-guys-movers' => ['name' => 'Little Guys Movers', 'source' => 'local', 'image_name' => 'little-guys-movers.png'],
      'optimum-white' => ['name' => 'Optimum - White Logo', 'source' => 'local', 'image_name' => 'optimum-white.svg'],
      'qshark-moving' => ['name' => 'Qshark Moving', 'source' => 'local', 'image_name' => 'atozvalleywidemovers.png'],
      'trosa-moving-and-storage' => ['name' => 'Trosa Moving and Storage', 'source' => 'local', 'image_name' => 'trosa-moving-and-storage.png'],

      'qustodio' => ['name' => 'Qustodio', 'source' => 'local', 'image_name' => 'qustodio.svg'],
      'idshield' => ['name' => 'IDShield', 'source' => 'local', 'image_name' => 'idshield.svg'],

      'affordablemoving' => ['name' => 'Affordable Moving', 'source' => 'local', 'image_name' => 'affordable-moving.png'],
      'bellhop' => ['name' => 'Bellhop', 'source' => 'local', 'image_name' => 'bellhop.svg'],
      'mwatmoving' => ['name' => 'MWAT Movers', 'source' => 'local', 'image_name' => 'mwat-moving.png'],
      'trekmovers' => ['name' => 'Trek Movers', 'source' => 'local', 'image_name' => 'trek-movers.png'],
      'nbkc-bank' => ['name' => 'NBKC Bank', 'source' => 'local', 'image_name' => 'nbkc-bank.svg'],
      'ars-technical' => ['name' => 'ARS Technica', 'source' => 'local', 'image_name' => 'arstechnica.svg'],
      'benton-institute' => ['name' => 'Benton Institute', 'source' => 'local', 'image_name' => 'bentoninstitute.svg'],
      'telecompetitor' => ['name' => 'Telecompetitor', 'source' => 'local', 'image_name' => 'telecompetitor.svg'],
      'xtream' => ['name' => 'Xtream', 'source' => 'local', 'image_name' => 'xtream.svg'],
      'lili' => ['name' => 'Lili', 'source' => 'local', 'image_name' => 'lili.png'],
      'starz' => ['name' => 'Starz', 'source' => 'local', 'image_name' => 'starz.svg'],
      'apple-tv-plus' => ['name' => 'Apple TV+', 'source' => 'local', 'image_name' => 'apple-tv-plus.png'],
      'britbox' => ['name' => 'BritBox', 'source' => 'local', 'image_name' => 'britbox.png'],
      'crunchy-roll' => ['name' => 'Crunchy Roll', 'source' => 'local', 'image_name' => 'crunchyroll.png'],
      'disney-plus' => ['name' => 'Disney Plus', 'source' => 'local', 'image_name' => 'disney-plus.png', 'redb' => 'disney-plus-logo'],
      'docplay' => ['name' => 'Docplay', 'source' => 'local', 'image_name' => 'docplay.png'],
      'foxtel-now' => ['name' => 'Foxtel Now', 'source' => 'local', 'image_name' => 'foxtel-now.png'],
      'hayu' => ['name' => 'Hayu', 'source' => 'local', 'image_name' => 'hayu.png'],
      'mubi' => ['name' => 'Mubi', 'source' => 'local', 'image_name' => 'mubi.png'],
      'paramount-plus' => ['name' => 'Paramount+', 'source' => 'local', 'image_name' => 'paramount-plus.png', 'redb' => 'paramount-plus-logo'],
      'prime-video' => ['name' => 'Prime Video', 'source' => 'local', 'image_name' => 'prime-video.png'],
      'shudder' => ['name' => 'Shudder', 'source' => 'local', 'image_name' => 'shudder.png'],
      'stan' => ['name' => 'Stan', 'source' => 'local', 'image_name' => 'stan.png'],
      'activ8me' => ['name' => 'Activ8me', 'source' => 'local', 'image_name' => 'activ8me.png'],
      'aldi-mobile' => ['name' => 'Aldi Mobile', 'source' => 'local', 'image_name' => 'aldi-mobile.png'],
      'amaysim' => ['name' => 'Amaysim', 'source' => 'local', 'image_name' => 'amaysim.svg'],
      'aussie-broadband' => ['name' => 'Aussie Broadband', 'source' => 'local', 'image_name' => 'aussie-broadband.png'],
      'barefoot' => ['name' => 'Barefoot', 'source' => 'local', 'image_name' => 'barefoot.svg'],
      'belong' => ['name' => 'Belong', 'source' => 'local', 'image_name' => 'belong.png'],
      'bendigo-bank-telco' => ['name' => 'Bendigo Bank Telco', 'source' => 'local', 'image_name' => 'bendigo-bank-telco.png'],
      'bigpond' => ['name' => 'Bigpond', 'source' => 'local', 'image_name' => 'bigpond.png'],
      'binge' => ['name' => 'Binge', 'source' => 'local', 'image_name' => 'binge.png'],
      'boost-mobile' => ['name' => 'Boost Mobile', 'source' => 'local', 'image_name' => 'boost-mobile.svg'],
      'c-mobile' => ['name' => 'C Mobile', 'source' => 'local', 'image_name' => 'c-mobile.png'],
      'catch-connect' => ['name' => 'Catch Connect', 'source' => 'local', 'image_name' => 'catch-connect.png'],
      'circles-life' => ['name' => 'Circles Life', 'source' => 'local', 'image_name' => 'circles-life.png'],
      'clear-networks' => ['name' => 'Clear Networks', 'source' => 'local', 'image_name' => 'clear-networks.svg'],
      'coles' => ['name' => 'Coles', 'source' => 'local', 'image_name' => 'coles.svg'],
      'commander' => ['name' => 'Commander', 'source' => 'local', 'image_name' => 'commander.svg'],
      'david-jones' => ['name' => 'David Jones', 'source' => 'local', 'image_name' => 'david-jones.svg'],
      'dodo' => ['name' => 'Dodo', 'source' => 'local', 'image_name' => 'dodo.svg'],
      'exetel' => ['name' => 'Exetel', 'source' => 'local', 'image_name' => 'exetel.svg'],
      'felix-mobile' => ['name' => 'Felix Mobile', 'source' => 'local', 'image_name' => 'felix-mobile.png'],
      'flip' => ['name' => 'Flip', 'source' => 'local', 'image_name' => 'flip.png'],
      'foxtel' => ['name' => 'Foxtel', 'source' => 'local', 'image_name' => 'foxtel.svg'],
      'go-talk' => ['name' => 'Go Talk', 'source' => 'local', 'image_name' => 'go-talk.png'],
      'gomo' => ['name' => 'Gomo', 'source' => 'local', 'image_name' => 'gomo.svg'],
      'hello-mobile' => ['name' => 'Hello Mobile', 'source' => 'local', 'image_name' => 'hello-mobile.png'],
      'huawei' => ['name' => 'Huawei', 'source' => 'local', 'image_name' => 'huawei.png'],
      'iinet' => ['name' => 'Iinet', 'source' => 'local', 'image_name' => 'iinet.svg'],
      'internode' => ['name' => 'Internode', 'source' => 'local', 'image_name' => 'internode.svg'],
      'iprimus' => ['name' => 'Iprimus', 'source' => 'local', 'image_name' => 'iprimus.svg'],
      'ipstar' => ['name' => 'Ipstar', 'source' => 'local', 'image_name' => 'ipstar.png'],
      'jb-hifi' => ['name' => 'JB Hifi', 'source' => 'local', 'image_name' => 'jb-hifi.svg'],
      'jeenee-mobile' => ['name' => 'Jeenee Mobile', 'source' => 'local', 'image_name' => 'jeenee-mobile.png'],
      'kayo-sports' => ['name' => 'Kayo Sports', 'source' => 'local', 'image_name' => 'kayo-sports.png'],
      'kogan-internet' => ['name' => 'Kogan Internet', 'source' => 'local', 'image_name' => 'kogan-internet.png'],
      'kogan-mobile' => ['name' => 'Kogan Mobile', 'source' => 'local', 'image_name' => 'kogan-mobile.png'],
      'lebara-mobile' => ['name' => 'Lebra Mobile', 'source' => 'local', 'image_name' => 'lebara-mobile.png'],
      'lyca-mobile' => ['name' => 'Lyca Mobile', 'source' => 'local', 'image_name' => 'lyca-mobile.svg'],
      'mate' => ['name' => 'Mate', 'source' => 'local', 'image_name' => 'mate.svg'],
      'microsoft' => ['name' => 'Microsoft', 'source' => 'local', 'image_name' => 'microsoft.png'],
      'moose-mobile' => ['name' => 'Moose Mobile', 'source' => 'local', 'image_name' => 'moose-mobile.png'],
      'my-net-fone' => ['name' => 'My Net Fone', 'source' => 'local', 'image_name' => 'my-net-fone.png'],
      'my-republic' => ['name' => 'My Republic', 'source' => 'local', 'image_name' => 'my-republic.svg'],
      'nu-mobile' => ['name' => 'Nu Mobile', 'source' => 'local', 'image_name' => 'nu-mobile.png'],
      'oppo' => ['name' => 'Oppo', 'source' => 'local', 'image_name' => 'oppo.svg'],
      'optus-sport' => ['name' => 'Optus Sport', 'source' => 'local', 'image_name' => 'optus-sport.png'],
      'optus' => ['name' => 'Optus', 'source' => 'local', 'image_name' => 'optus.svg'],
      'ovo' => ['name' => 'Ovo', 'source' => 'local', 'image_name' => 'ovo.png'],
      'pennytel' => ['name' => 'Pennytel', 'source' => 'local', 'image_name' => 'pennytel.png'],
      'redbull-mobile' => ['name' => 'Redbull Mobile', 'source' => 'local', 'image_name' => 'redbull-mobile.svg'],
      'skymesh' => ['name' => 'Skymesh', 'source' => 'local', 'image_name' => 'skymesh.svg'],
      'sony' => ['name' => 'Sony', 'source' => 'local', 'image_name' => 'sony.svg'],
      'southern-phone' => ['name' => 'Southern Phone', 'source' => 'local', 'image_name' => 'southern-phone.png'],
      'spintel' => ['name' => 'Spintel', 'source' => 'local', 'image_name' => 'spintel.png'],
      'start-broadband' => ['name' => 'Start Broadband', 'source' => 'local', 'image_name' => 'start-broadband.svg'],
      'superloop' => ['name' => 'Superloop', 'source' => 'local', 'image_name' => 'superloop.svg'],
      'tangerine-telcom' => ['name' => 'Tangerine Telcom', 'source' => 'local', 'image_name' => 'tangerine-telcom.svg'],
      'telechoice' => ['name' => 'Telechoice', 'source' => 'local', 'image_name' => 'telechoice.png'],
      'telstra' => ['name' => 'Telstra', 'source' => 'local', 'image_name' => 'telstra.png'],
      'think-mobile' => ['name' => 'Think Mobile', 'source' => 'local', 'image_name' => 'think-mobile.png'],
      'tpg' => ['name' => 'TPG', 'source' => 'local', 'image_name' => 'tpg.svg'],
      'vaya' => ['name' => 'Vaya', 'source' => 'local', 'image_name' => 'vaya.svg'],
      'vodafone' => ['name' => 'Vodaphone', 'source' => 'local', 'image_name' => 'vodafone.svg'],
      'westnet' => ['name' => 'Westnet', 'source' => 'local', 'image_name' => 'westnet.svg'],
      'woolworths-mobile' => ['name' => 'Woolsworth Mobile', 'source' => 'local', 'image_name' => 'woolworths-mobile.png'],
      'yomojo' => ['name' => 'Yomojo', 'source' => 'local', 'image_name' => 'yomojo.png'],
      'consumercellular' => ['name' => 'Consumer Cellular', 'source' => 'local', 'image_name' => 'consumercellular.png'],
      'cyberghost' => ['name' => 'Cyberghost', 'source' => 'local', 'image_name' => 'cyberghost.svg'],
      'genmobile' => ['name' => 'Gen Mobile', 'source' => 'local', 'image_name' => 'genmobile.png'],
      'googlefi' => ['name' => 'Google Fi', 'source' => 'local', 'image_name' => 'googlefi.png'],
      'googlemeet' => ['name' => 'Google Meet', 'source' => 'local', 'image_name' => 'googlemeet.svg'],
      'greatcall' => ['name' => 'Great Call', 'source' => 'local', 'image_name' => 'greatcall.svg'],
      'hotspotshield' => ['name' => 'Hotspot Shield', 'source' => 'local', 'image_name' => 'hotspotshield.svg'],
      'ipvanish' => ['name' => 'Ip Vanish', 'source' => 'local', 'image_name' => 'ipvanish.svg'],
      'keepsolid' => ['name' => 'Keep Solid', 'source' => 'local', 'image_name' => 'keepsolid.svg'],
      'metro' => ['name' => 'Metro', 'source' => 'local', 'image_name' => 'metro.svg'],
      'mintmobile' => ['name' => 'Mint Mobile', 'source' => 'local', 'image_name' => 'mintmobile.svg'],
      'mullvadvpn' => ['name' => 'Mullvad VPN', 'source' => 'local', 'image_name' => 'mullvadvpn.svg'],
      'peacocktv' => ['name' => 'PeacockTV', 'source' => 'local', 'image_name' => 'peacocktv.svg'],
      'plutotv' => ['name' => 'PlutoTV', 'source' => 'local', 'image_name' => 'plutotv.svg'],
      'privateinternetaccessvpn' => ['name' => 'Private Internet Access VPN', 'source' => 'local', 'image_name' => 'privateinternetaccessvpn.png'],
      'protonvpn' => ['name' => 'ProtonVPN', 'source' => 'local', 'image_name' => 'protonvpn.svg'],
      'puretalk' => ['name' => 'PureTalk', 'source' => 'local', 'image_name' => 'puretalk.svg'],
      'purevpn' => ['name' => 'PureVPN', 'source' => 'local', 'image_name' => 'purevpn.png'],
      'reachmobile' => ['name' => 'ReachMobile', 'source' => 'local', 'image_name' => 'reachmobile.png'],
      'reolink' => ['name' => 'Reo Link', 'source' => 'local', 'image_name' => 'reolink.png'],
      'sprint' => ['name' => 'Sprint', 'source' => 'local', 'image_name' => 'sprint.svg'],
      'surfshark' => ['name' => 'Surfshark', 'source' => 'local', 'image_name' => 'surfshark.svg'],
      'tello' => ['name' => 'Tello', 'source' => 'local', 'image_name' => 'tello.svg'],
      'totalwireless' => ['name' => 'Total Wireless', 'source' => 'local', 'image_name' => 'totalwireless.png'],
      'tracfone' => ['name' => 'Tracfone', 'source' => 'local', 'image_name' => 'tracfone.png'],
      'tunnelbear' => ['name' => 'Tunnel Bear', 'source' => 'local', 'image_name' => 'tunnelbear.svg'],
      'ultramobile' => ['name' => 'Ultra Mobile', 'source' => 'local', 'image_name' => 'ultramobile.svg'],
      'ultrasurf' => ['name' => 'Ultrasurf', 'source' => 'local', 'image_name' => 'ultrasurf.png'],
      'usmobile' => ['name' => 'US Mobile', 'source' => 'local', 'image_name' => 'usmobile.svg'],
      'vpnsecure' => ['name' => 'VPN Secure', 'source' => 'local', 'image_name' => 'vpnsecure.svg'],
      'vyprvpn' => ['name' => 'Vyprvpn', 'source' => 'local', 'image_name' => 'vyprvpn.svg'],
      'youtube' => ['name' => 'Youtube', 'source' => 'local', 'image_name' => 'youtube.svg'],
      'windstream' => ['name' => 'Windstream', 'source' => 'local', 'image_name' => 'windstream.svg'],
      'netflix' => ['name' => 'Netflix', 'source' => 'local', 'image_name' => 'netflix.svg', 'redb' => 'netflix-logo'],
      'earthlink' => ['name' => 'Earthlink', 'source' => 'local', 'image_name' => 'earthlink.svg', 'redb' => 'earthlink-logo'],
      'starlink' => ['name' => 'Starlink', 'source' => 'local', 'image_name' => 'starlink.svg'],
      'visible' => ['name' => 'Visible', 'source' => 'local', 'image_name' => 'visible.svg'],
      'unlimitedville' => ['name' => 'Unlimitedville', 'source' => 'local', 'image_name' => 'unlimitedville.svg'],
      'skyroam' => ['name' => 'Skyroam', 'source' => 'local', 'image_name' => 'skyroam.svg'],
      'skype' => ['name' => 'Skype', 'source' => 'local', 'image_name' => 'skype.svg'],
      'simple-mobile' => ['name' => 'Simple Mobile', 'source' => 'local', 'image_name' => 'simple-mobile.svg'],
      'mobile-sat' => ['name' => 'Mobile Sat', 'source' => 'local', 'image_name' => 'mobile-sat.png'],
      'alfa-network' => ['name' => 'Alfa Network', 'source' => 'local', 'image_name' => 'alfa-network.svg'],
      'att' => ['name' => 'ATT', 'source' => 'local', 'image_name' => 'att.svg', 'redb' => 'att-logo'],
      'att-pr' => ['name' => 'ATT Preferred Dealer', 'source' => 'local', 'image_name' => 'att-pr.svg'],
      'att-tv' => ['name' => 'ATT TV', 'source' => 'local', 'image_name' => 'att-tv.svg', 'redb' => 'att-tv-logo'],
      'centurylink-ar' => ['name' => 'Centurlink Authorized Sales Agent', 'source' => 'local', 'image_name' => 'centurylink-ar.svg'],
      'centurylink' => ['name' => 'Centurylink', 'source' => 'local', 'image_name' => 'centurylink.svg', 'redb' => 'centurylink-logo'],
      'cox-ar' => ['name' => 'Cox Authorized Retailer', 'source' => 'local', 'image_name' => 'cox-ar.svg', 'redb' => 'cox-logo'],
      'cox-normal' => ['name' => 'Cox', 'source' => 'local', 'image_name' => 'cox.svg'],
      'cricket' => ['name' => 'Cricket', 'source' => 'local', 'image_name' => 'cricket.svg'],
      'directv-ar' => ['name' => 'Directv Authoried Dealer', 'source' => 'local', 'image_name' => 'directv-ar.svg'],
      'directv' => ['name' => 'Directv', 'source' => 'local', 'image_name' => 'directv-blue.svg', 'redb' => 'directv-logo'],
      'dish-ar' => ['name' => 'Dish Authorized Retailer', 'source' => 'local', 'image_name' => 'dish-ar.svg', 'redb' => 'dish-logo'],
      'dish' => ['name' => 'Dish', 'source' => 'local', 'image_name' => 'dish.svg'],
      'frontier-ar' => ['name' => 'Frontier Authorized Sales Agent', 'source' => 'local', 'image_name' => 'frontier-ar.svg'],
      'garmin' => ['name' => 'Garmin', 'source' => 'local', 'image_name' => 'garmin.svg'],
      'google-fiber' => ['name' => 'Google Fiber', 'source' => 'local', 'image_name' => 'google-fiber.svg', 'redb' => 'google-fiber-logo'],
      'highspeedinternet' => ['name' => 'HighSpeedInternet', 'source' => 'local', 'image_name' => 'high-speed-internet.svg'],
      'hughesnet-ar' => ['name' => 'HughesNet Authorized Retailer', 'source' => 'local', 'image_name' => 'hughesnet-ar.svg'],
      'hughesnet' => ['name' => 'HughesNet', 'source' => 'local', 'image_name' => 'hughesnet.svg', 'redb' => 'hughesnet-logo'],
      'iridium' => ['name' => 'Iridium', 'source' => 'local', 'image_name' => 'iridium.png'],
      'king' => ['name' => 'King', 'source' => 'local', 'image_name' => 'king.png'],
      'ladybug-wireless' => ['name' => 'Ladybug Wireless', 'source' => 'local', 'image_name' => 'ladybug-wireless.png'],
      'mediacom-ar' => ['name' => 'Mediacom Authorized Retailer', 'source' => 'local', 'image_name' => 'mediacom-ar.svg'],
      'mediacom' => ['name' => 'Mediacom', 'source' => 'local', 'image_name' => 'mediacom.svg', 'redb' => 'mediacom-logo'],
      'mint-mobile' => ['name' => 'Mint Mobile', 'source' => 'local', 'image_name' => 'mint-mobile.svg'],
      'nomad-internet' => ['name' => 'Nomad Internet', 'source' => 'local', 'image_name' => 'nomad-internet.png'],
      'optimum-ar' => ['name' => 'Optimum Authorized Reseller', 'source' => 'local', 'image_name' => 'optimum-ar.svg'],
      'optimum' => ['name' => 'Optimum', 'source' => 'local', 'image_name' => 'optimum.svg', 'redb' => 'optimum-logo'],
      'orby-tv' => ['name' => 'Orby TV', 'source' => 'local', 'image_name' => 'orby-tv.png'],
      'republic-wireless' => ['name' => 'Republic Wireless', 'source' => 'local', 'image_name' => 'republic-wireless.png'],
      'rise-broadband' => ['name' => 'Rise Broadband', 'source' => 'local', 'image_name' => 'rise-broadband.svg'],
      'spectrum-ar' => ['name' => 'Spectum Authorized Reseller', 'source' => 'local', 'image_name' => 'spectrum-ar.svg'],
      'spectrum' => ['name' => 'Spectrum', 'source' => 'local', 'image_name' => 'spectrum.svg', 'redb' => 'spectrum-logo'],
      'tmobile' => ['name' => 'T Mobile', 'source' => 'local', 'image_name' => 'tmobile.svg'],
      'ubifi' => ['name' => 'UbiFi', 'source' => 'local', 'image_name' => 'ubifi.png'],
      'verizon-authorized-dealer' => ['name' => 'Verizon Authorized Dealer', 'source' => 'local', 'image_name' => 'verizon-ar.svg', 'redb' => 'verizon-logo'],
      'verizon' => ['name' => 'Verizon', 'source' => 'local', 'image_name' => 'verizon.svg'],
      'viasat-ar' => ['name' => 'Viasat Authorized Retailer', 'source' => 'local', 'image_name' => 'viasat-ar.svg'],
      'wahoo' => ['name' => 'Wahoo Internet', 'source' => 'local', 'image_name' => 'wahoo.png'],
      'weboost' => ['name' => 'Weboost', 'source' => 'local', 'image_name' => 'weboost.svg'],
      'winegard' => ['name' => 'Winegard', 'source' => 'local', 'image_name' => 'winegard.png'],
      'xfinity-ar' => ['name' => 'Xfinity Authorized Retailer', 'source' => 'local', 'image_name' => 'xfinity-ar.svg'],
      'xfinity' => ['name' => 'Xfinity', 'source' => 'local', 'image_name' => 'xfinity.svg', 'redb' => 'xfinity-logo'],
      '1800gotjunk' => ['name' => '1800gotjunk', 'source' => 'local', 'image_name' => '1800gotjunk.svg'],
      '1800packrat' => ['name' => '1800packrat', 'source' => 'local', 'image_name' => '1800packrat.svg'],
      'allied' => ['name' => 'allied', 'source' => 'local', 'image_name' => 'allied.svg'],
      'allmysons' => ['name' => 'allmysons', 'source' => 'local', 'image_name' => 'allmysons.svg'],
      'americanvanlines' => ['name' => 'americanvanlines', 'source' => 'local', 'image_name' => 'americanvanlines.svg'],
      'amerifreight' => ['name' => 'amerifreight', 'source' => 'local', 'image_name' => 'amerifreight.svg'],
      'atlas' => ['name' => 'atlas', 'source' => 'local', 'image_name' => 'atlas.svg'],
      'bargainautotransport' => ['name' => 'bargainautotransport', 'source' => 'local', 'image_name' => 'bargainautotransport.svg'],
      'bekins' => ['name' => 'bekins', 'source' => 'local', 'image_name' => 'bekins.svg'],
      'bims' => ['name' => 'bims', 'source' => 'local', 'image_name' => 'bims.svg'],
      'budget' => ['name' => 'budget', 'source' => 'local', 'image_name' => 'budget.svg'],
      'collegehunks' => ['name' => 'collegehunks', 'source' => 'local', 'image_name' => 'college-hunks.png'],
      'cubesmart' => ['name' => 'cubesmart', 'source' => 'local', 'image_name' => 'cubesmart.svg'],
      'dedicatedvanlines' => ['name' => 'dedicatedvanlines', 'source' => 'local', 'image_name' => 'dedicatedvanlines.png'],
      'enterprisetruckrental' => ['name' => 'enterprisetruckrental', 'source' => 'local', 'image_name' => 'enterprisetruckrental.png'],
      'extraspace' => ['name' => 'extraspace', 'source' => 'local', 'image_name' => 'extraspace.svg'],
      'imrg' => ['name' => 'imrg', 'source' => 'local', 'image_name' => 'imrg.svg'],
      'internationalvanlines' => ['name' => 'internationalvanlines', 'source' => 'local', 'image_name' => 'internationalvanlines.png'],
      'neighbor' => ['name' => 'Neighbor', 'source' => 'local', 'image_name' => 'neighbor.png'],
      'home-depot' => ['name' => 'Home Depot', 'source' => 'local', 'image_name' => 'home-depot.png'],
      'american-auto-shipping' => ['name' => 'American Auto Shipping', 'source' => 'local', 'image_name' => 'american-auto-shipping.png'],
      'junkking' => ['name' => 'junkking', 'source' => 'local', 'image_name' => 'junkking.svg'],
      'loadupuunkremoval' => ['name' => 'loadupuunkremoval', 'source' => 'local', 'image_name' => 'loadupuunkremoval.png'],
      'Montway-Center-Color' => ['name' => 'Montway-Center-Color', 'source' => 'local', 'image_name' => 'Montway-Center-Color.svg'],
      'northamerican' => ['name' => 'northamerican', 'source' => 'local', 'image_name' => 'northamerican.svg'],
      'penske' => ['name' => 'penske', 'source' => 'local', 'image_name' => 'penske.svg'],
      'pods' => ['name' => 'pods', 'source' => 'local', 'image_name' => 'pods.svg'],
      'publicstorage' => ['name' => 'publicstorage', 'source' => 'local', 'image_name' => 'publicstorage.svg'],
      'safeway' => ['name' => 'safeway', 'source' => 'local', 'image_name' => 'safeway.png'],
      'sherpa' => ['name' => 'sherpa', 'source' => 'local', 'image_name' => 'sherpa.svg'],
      'shipacardirect' => ['name' => 'shipacardirect', 'source' => 'local', 'image_name' => 'shipacardirect.svg'],
      'simplyselfstorage' => ['name' => 'simplyselfstorage', 'source' => 'local', 'image_name' => 'simplyselfstorage.png'],
      'smartbox' => ['name' => 'smartbox', 'source' => 'local', 'image_name' => 'smartbox.svg'],
      'solomonandsons' => ['name' => 'solomonandsons', 'source' => 'local', 'image_name' => 'solomonandsons.svg'],
      'taskrabbit' => ['name' => 'taskrabbit', 'source' => 'local', 'image_name' => 'taskrabbit.svg'],
      'twomen' => ['name' => 'twomen', 'source' => 'local', 'image_name' => 'two-men-and-a-truck.png'],
      'uhaul' => ['name' => 'uhaul', 'source' => 'local', 'image_name' => 'uhaul.svg'],
      'united' => ['name' => 'united', 'source' => 'local', 'image_name' => 'united.svg'],
      'upack' => ['name' => 'upack', 'source' => 'local', 'image_name' => 'upack.svg'],
      'uship' => ['name' => 'uship', 'source' => 'local', 'image_name' => 'uship.svg'],
      'wastemanagement' => ['name' => 'wastemanagement', 'source' => 'local', 'image_name' => 'wastemanagement.svg'],
      'zippyshell' => ['name' => 'zippyshell', 'source' => 'local', 'image_name' => 'zippyshell.svg'],
      'angelsense' => ['name' => 'AngelSense', 'source' => 'local', 'image_name' => 'angelsense.png'],
      'arlo-alt' => ['name' => 'Arlo Alt', 'source' => 'local', 'image_name' => 'arlo-alt.svg'],
      'avg' => ['name' => 'AVG', 'source' => 'local', 'image_name' => 'avg.png'],
      'bark' => ['name' => 'Bark', 'source' => 'local', 'image_name' => 'bark.svg'],
      'bayalarm' => ['name' => 'Bay Alarm', 'source' => 'local', 'image_name' => 'bayalarm.svg'],
      'bitdefender' => ['name' => 'Bitdefender', 'source' => 'local', 'image_name' => 'bitdefender.svg'],
      'blink' => ['name' => 'Blink', 'source' => 'local', 'image_name' => 'blink.png'],
      'brinks' => ['name' => 'Brinks', 'source' => 'local', 'image_name' => 'brinks.svg'],
      'dashlane' => ['name' => 'Dashlane', 'source' => 'local', 'image_name' => 'dashlane.svg'],
      'eset' => ['name' => 'Eset', 'source' => 'local', 'image_name' => 'eset.svg'],
      'experian' => ['name' => 'Experian', 'source' => 'local', 'image_name' => 'experian.svg'],
      'findster' => ['name' => 'Findster', 'source' => 'local', 'image_name' => 'findster.png'],
      'getsafe' => ['name' => 'Get Safe', 'source' => 'local', 'image_name' => 'get-safe.svg'],
      'identity-force' => ['name' => 'Identity Force', 'source' => 'local', 'image_name' => 'identity-force.png'],
      'kaspersky' => ['name' => 'Kaspersky', 'source' => 'local', 'image_name' => 'kaspersky.svg'],
      'keepass' => ['name' => 'Keepass', 'source' => 'local', 'image_name' => 'keepass.png'],
      'lastpass' => ['name' => 'LastPass', 'source' => 'local', 'image_name' => 'lastpass.svg'],
      'lifefone' => ['name' => 'LifeFone', 'source' => 'local', 'image_name' => 'lifefone.svg'],
      'lifelock' => ['name' => 'LifeLock', 'source' => 'local', 'image_name' => 'lifelock.svg'],
      'link-interactive' => ['name' => 'link Interactive', 'source' => 'local', 'image_name' => 'link-interactive.svg', 'redb' => 'link-interactive-logo'],
      'medical-guardian' => ['name' => 'Medical Guardian', 'source' => 'local', 'image_name' => 'medical-guardian.svg'],
      'mobilehelp' => ['name' => 'MobileHelp', 'source' => 'local', 'image_name' => 'mobilehelp.png'],
      'netnanny' => ['name' => 'Net Nanny', 'source' => 'local', 'image_name' => 'netnanny.png'],
      'nord-vpn' => ['name' => 'Nord VPN', 'source' => 'local', 'image_name' => 'nord-vpn.svg'],
      'norton-alt' => ['name' => 'Norton Alt', 'source' => 'local', 'image_name' => 'norton-alt.png'],
      'philipslifeline' => ['name' => 'Philips Lifeline', 'source' => 'local', 'image_name' => 'philips-lifeline.png'],
      'protect-america' => ['name' => 'Protect America', 'source' => 'local', 'image_name' => 'protect-america.png', 'redb' => 'protect-america-logo'],
      'relay' => ['name' => 'Relay', 'source' => 'local', 'image_name' => 'relay.png'],
      'reliashield' => ['name' => 'ReliaShield', 'source' => 'local', 'image_name' => 'reliashield.png'],
      'total-security' => ['name' => 'Total Security', 'source' => 'local', 'image_name' => 'total-security.png'],
      'verisure' => ['name' => 'Verisure', 'source' => 'local', 'image_name' => 'verisure.png'],
      'westminster' => ['name' => 'Westminster', 'source' => 'local', 'image_name' => 'westminster.svg'],
      'wyze' => ['name' => 'WYZE', 'source' => 'local', 'image_name' => 'wyze.svg'],
      'yale.svg' => ['name' => 'Yale', 'source' => 'local', 'image_name' => 'yale.svg'],
      '1-1' => ['name' => '1&1', 'source' => 'local', 'image_name' => '1_1.svg'],
      '1-voip' => ['name' => '1-VoIP', 'source' => 'local', 'image_name' => '1-voip.jpg'],
      '360-training' => ['name' => '360 Training', 'source' => 'local', 'image_name' => '360-training.svg'],
      'a2hosting' => ['name' => 'A2 Hosting', 'source' => 'local', 'image_name' => 'a2hosting.jpg'],
      'Acme' => ['name' => 'Acme', 'source' => 'local', 'image_name' => 'acme.jpg'],
      'adp' => ['name' => 'ADP', 'source' => 'local', 'image_name' => 'adp.svg'],
      'airtable' => ['name' => 'Airtable', 'source' => 'local', 'image_name' => 'airtable.svg'],
      'albert' => ['name' => 'Albert', 'source' => 'local', 'image_name' => 'albert.svg'],
      'almyta' => ['name' => 'Almyta', 'source' => 'local', 'image_name' => 'almyta.jpg'],
      'ambur' => ['name' => 'Ambur', 'source' => 'local', 'image_name' => 'ambur.jpg'],
      'american-business-bank' => ['name' => 'American Business Bank', 'source' => 'local', 'image_name' => 'american-business-bank.jpg'],
      'apptivo' => ['name' => 'Apptivo', 'source' => 'local', 'image_name' => 'apptivo.svg'],
      'arlo' => ['name' => 'Arlo', 'source' => 'local', 'image_name' => 'arlo.svg'],
      'apriori' => ['name' => 'Apriori', 'source' => 'local', 'image_name' => 'apriori.jpg'],
      'asana' => ['name' => 'Asana', 'source' => 'local', 'image_name' => 'asana.jpg'],
      'asana' => ['name' => 'Asana', 'source' => 'local', 'image_name' => 'asana.jpg'],
      'asian-woman-giving-circle' => ['name' => 'Asian Woman Giving Circle', 'source' => 'local', 'image_name' => 'asian-woman-giving-circle.jpg'],
      'astra' => ['name' => 'Astra', 'source' => 'local', 'image_name' => 'astra.svg'],
      'attbusiness' => ['name' => 'AT&T Business', 'source' => 'local', 'image_name' => 'attbusiness.svg'],
      'avada' => ['name' => 'Avada', 'source' => 'local', 'image_name' => 'avada.jpg'],
      'avant' => ['name' => 'Avant', 'source' => 'local', 'image_name' => 'avant.jpg'],
      'avaza' => ['name' => 'Avaza', 'source' => 'local', 'image_name' => 'avaza.jpg'],
      'axos' => ['name' => 'Axos Bank', 'source' => 'local', 'image_name' => 'axos.svg'],
      'azlo' => ['name' => 'Azlo', 'source' => 'local', 'image_name' => 'azlo.svg'],
      'backlog' => ['name' => 'Backlog', 'source' => 'local', 'image_name' => 'backlog.jpg'],
      'balboa-capital' => ['name' => 'Balboa Capital', 'source' => 'local', 'image_name' => 'balboa-capital.jpg'],
      'bamboohr' => ['name' => 'bambooHR', 'source' => 'local', 'image_name' => 'bamboohr.svg'],
      'bandzoogle' => ['name' => 'Bandzoogle', 'source' => 'local', 'image_name' => 'bandzoogle.jpg'],
      'basecamp' => ['name' => 'Basecamp', 'source' => 'local', 'image_name' => 'basecamp.jpg'],
      'bbva' => ['name' => 'BBVA', 'source' => 'local', 'image_name' => 'bbva.svg'],
      'beaver-builder' => ['name' => 'Beaver Builder', 'source' => 'local', 'image_name' => 'beaver-builder.jpg'],
      'bench' => ['name' => 'Bench', 'source' => 'local', 'image_name' => 'bench.jpg'],
      'berkshire-hathaway' => ['name' => 'Berkshire Hathaway', 'source' => 'local', 'image_name' => 'berkshire-hathaway.jpg'],
      'betteraccounting' => ['name' => 'Better Accounting', 'source' => 'local', 'image_name' => 'betteraccounting.svg'],
      'beyond' => ['name' => 'Beyond', 'source' => 'local', 'image_name' => 'beyond.jpg'],
      'bindo' => ['name' => 'Bindo', 'source' => 'local', 'image_name' => 'bindo.jpg'],
      'biznamewiz' => ['name' => 'BizNameWiz', 'source' => 'local', 'image_name' => 'biznamewiz.jpg'],
      'blink' => ['name' => 'Blink', 'source' => 'local', 'image_name' => 'blink.jpg'],
      'bloomfield' => ['name' => 'Bloomfield', 'source' => 'local', 'image_name' => 'bloomfield.svg'],
      'blue-by-adt' => ['name' => 'Blue by ADT', 'source' => 'local', 'image_name' => 'blue-by-adt.svg'],
      'bluehost' => ['name' => 'BlueHost', 'source' => 'local', 'image_name' => 'bluehost.svg'],
      'bluevine' => ['name' => 'BlueVine', 'source' => 'local', 'image_name' => 'bluevine.svg'],
      'boost-mobile' => ['name' => 'Boost Mobile', 'source' => 'local', 'image_name' => 'boost-mobile.jpg'],
      'brandroot' => ['name' => 'Brandroot', 'source' => 'local', 'image_name' => 'brandroot.jpg'],
      'boston-womens-foundation' => ['name' => 'Boston Womens Foundation', 'source' => 'local', 'image_name' => 'boston-womens-foundation.jpg'],
      'business-plan-pro' => ['name' => 'Business Plan Pro', 'source' => 'local', 'image_name' => 'business-plan-pro.jpg'],
      'canary' => ['name' => 'Canary', 'source' => 'local', 'image_name' => 'canary.jpg'],
      'can-capital' => ['name' => 'Can Capital', 'source' => 'local', 'image_name' => 'can-capital.jpg'],
      'capital-one' => ['name' => 'Capital One', 'source' => 'local', 'image_name' => 'capital-one.svg'],
      'careerbuilder' => ['name' => 'Career Builder', 'source' => 'local', 'image_name' => 'careerbuilder.svg'],
      'cartier-womens-initiative' => ['name' => 'Cartier Womens Initiative', 'source' => 'local', 'image_name' => 'cartier-womens-initiative.png'],
      'charles-schwab' => ['name' => 'Charles Schwab', 'source' => 'local', 'image_name' => 'charles-schwab.svg'],
      'chubb' => ['name' => 'Chubb', 'source' => 'local', 'image_name' => 'chubb.jpg'],
      'circleup' => ['name' => 'CircleUp', 'source' => 'local', 'image_name' => 'circleup.jpg'],
      'cisco' => ['name' => 'Cisco', 'source' => 'local', 'image_name' => 'cisco.svg'],
      'citi' => ['name' => 'Citi', 'source' => 'local', 'image_name' => 'citi.svg'],
      'citizens' => ['name' => 'Citizens', 'source' => 'local', 'image_name' => 'citizens.jpg'],
      'claritymoney' => ['name' => 'Clarity Money', 'source' => 'local', 'image_name' => 'claritymoney.png'],
      'clearcompany' => ['name' => 'ClearCompany', 'source' => 'local', 'image_name' => 'clearcompany.jpg'],
      'clopton' => ['name' => 'Clopton', 'source' => 'local', 'image_name' => 'clopton.jpg'],
      'clover' => ['name' => 'Clover', 'source' => 'local', 'image_name' => 'clover.jpg'],
      'cloudbooks' => ['name' => 'Cloudbooks', 'source' => 'local', 'image_name' => 'cloudbooks.jpg'],
      'comcast-business' => ['name' => 'Comcast Business', 'source' => 'local', 'image_name' => 'comcast-business.svg'],
      'corevest' => ['name' => 'Corevest', 'source' => 'local', 'image_name' => 'corevest.jpg'],
      'coschedule' => ['name' => 'Coschedule', 'source' => 'local', 'image_name' => 'coschedule.svg'],
      'countabout' => ['name' => 'Count About', 'source' => 'local', 'image_name' => 'countabout.jpg'],
      'cox' => ['name' => 'Cox Business', 'source' => 'local', 'image_name' => 'cox.jpg'],
      'cox-homelife' => ['name' => 'Cox Homelife', 'source' => 'local', 'image_name' => 'cox-homelife.svg'],
      'crest-capital' => ['name' => 'Crest Capital', 'source' => 'local', 'image_name' => 'crest-capital.jpg'],
      'cricket' => ['name' => 'Cricket', 'source' => 'local', 'image_name' => 'cricket.svg'],
      'degreed' => ['name' => 'Degreed', 'source' => 'local', 'image_name' => 'degreed.png'],
      'desktime' => ['name' => 'DeskTime', 'source' => 'local', 'image_name' => 'desktime.png'],
      'dharma' => ['name' => 'Dharma', 'source' => 'local', 'image_name' => 'dharma.jpg'],
      'directv-for-business' => ['name' => 'Directv For Business', 'source' => 'local', 'image_name' => 'directv-for-business.jpg'],
      'divi' => ['name' => 'Divi', 'source' => 'local', 'image_name' => 'divi.jpg'],
      'domain-com' => ['name' => 'Domain.com', 'source' => 'local', 'image_name' => 'domain-com.jpg'],
      'dotomator' => ['name' => 'Dot-o-mator', 'source' => 'local', 'image_name' => 'dotomator.jpg'],
      'dreamhost' => ['name' => 'DreamHost', 'source' => 'local', 'image_name' => 'dreamhost.png'],
      'dynadot' => ['name' => 'Dynadot', 'source' => 'local', 'image_name' => 'dynadot.jpg'],
      'easyprojects' => ['name' => 'Easy Projects', 'source' => 'local', 'image_name' => 'easyprojects.svg'],
      'eduma' => ['name' => 'Eduma', 'source' => 'local', 'image_name' => 'eduma.jpg'],
      'efile' => ['name' => 'Efile', 'source' => 'local', 'image_name' => 'efile.png'],
      'eileen-fisher' => ['name' => 'Eileen Fisher', 'source' => 'local', 'image_name' => 'eileen-fisher.svg'],
      'elavon' => ['name' => 'Elavon', 'source' => 'local', 'image_name' => 'elavon.jpg'],
      'elegant-themes' => ['name' => 'Elegant Themes', 'source' => 'local', 'image_name' => 'elegant-themes.svg'],
      'esmart-paycheck' => ['name' => 'eSmart Paycheck', 'source' => 'local', 'image_name' => 'esmart-paycheck.jpg'],
      'evernote' => ['name' => 'Evernote', 'source' => 'local', 'image_name' => 'evernote.svg'],
      'everydollar' => ['name' => 'Every Dollar', 'source' => 'local', 'image_name' => 'everydollar.jpg'],
      'expedia' => ['name' => 'Expedia', 'source' => 'local', 'image_name' => 'expedia.svg'],
      'expensify' => ['name' => 'Expensify', 'source' => 'local', 'image_name' => 'expensify.svg'],
      'expert-rating' => ['name' => 'Expert Rating', 'source' => 'local', 'image_name' => 'expert-rating.png'],
      'express-account' => ['name' => 'Express Account', 'source' => 'local', 'image_name' => 'express-account.jpg'],
      'ez-office-inventory' => ['name' => 'EZ Office Inventory', 'source' => 'local', 'image_name' => 'ez-office-inventory.jpg'],
      'fatcow' => ['name' => 'Fatcow', 'source' => 'local', 'image_name' => 'fatcow.jpg'],
      'fattmerchant' => ['name' => 'Fatt Merchant', 'source' => 'local', 'image_name' => 'fattmerchant.png'],
      'fedex' => ['name' => 'FedEx', 'source' => 'local', 'image_name' => 'fedex.svg'],
      'firewalla' => ['name' => 'Firewalla', 'source' => 'local', 'image_name' => 'firewalla.jpg'],
      'firstrade' => ['name' => 'Firstrade', 'source' => 'local', 'image_name' => 'firstrade.jpg'],
      'fis' => ['name' => 'FIS', 'source' => 'local', 'image_name' => 'fis.svg'],
      'fishbowl' => ['name' => 'Fishbowl', 'source' => 'local', 'image_name' => 'fishbowl.png'],
      'flatworld' => ['name' => 'Flatworld', 'source' => 'local', 'image_name' => 'flatworld.jpg'],
      'flint' => ['name' => 'Flint', 'source' => 'local', 'image_name' => 'flint.jpg'],
      'flip-funding' => ['name' => 'Flip Funding', 'source' => 'local', 'image_name' => 'flip-funding.jpg'],
      'flywheel' => ['name' => 'Flywheel', 'source' => 'local', 'image_name' => 'flywheel.svg'],
      'fora' => ['name' => 'Fora', 'source' => 'local', 'image_name' => 'fora.svg'],
      'format' => ['name' => 'Format', 'source' => 'local', 'image_name' => 'format.svg'],
      'freeagent' => ['name' => 'FreeAgent', 'source' => 'local', 'image_name' => 'freeagent.svg'],
      'free-tax-usa' => ['name' => 'Free Tax USA', 'source' => 'local', 'image_name' => 'freetaxusa.svg'],
      'frontier' => ['name' => 'Frontier', 'source' => 'local', 'image_name' => 'frontier.svg', 'redb' => 'frontier-logo'],
      'frontier-black' => ['name' => 'Frontier (Black)', 'source' => 'local', 'image_name' => 'frontier-black.svg'],
      'fundable' => ['name' => 'Fundable', 'source' => 'local', 'image_name' => 'fundable.jpg'],
      'getsocio' => ['name' => 'Getsocio', 'source' => 'local', 'image_name' => 'getsocio.jpg'],
      'girlboss-foundation' => ['name' => 'Girlboss Foundation', 'source' => 'local', 'image_name' => 'girlboss-foundation.jpg'],
      'glip' => ['name' => 'Glip', 'source' => 'local', 'image_name' => 'glip.jpg'],
      'gnucash' => ['name' => 'GnuCash', 'source' => 'local', 'image_name' => 'gnucash.jpg'],
      'goco' => ['name' => 'Goco', 'source' => 'local', 'image_name' => 'goco.png'],
      'gofundme' => ['name' => 'gofundme', 'source' => 'local', 'image_name' => 'gofundme.svg'],
      'goodbudget' => ['name' => 'Good Budget', 'source' => 'local', 'image_name' => 'goodbudget.jpg'],
      'googlesites' => ['name' => 'Google Sites', 'source' => 'local', 'image_name' => 'googlesites.jpg'],
      'go-to-meeting-log-me-in' => ['name' => 'GoToMeeting by LogMeIn', 'source' => 'local', 'image_name' => 'go-to-meeting-log-me-in.jpg'],
      'go-to-meeting' => ['name' => 'GoToMeeting', 'source' => 'local', 'image_name' => 'go-to-meeting.svg'],
      'grasshopper' => ['name' => 'Grasshopper', 'source' => 'local', 'image_name' => 'grasshopper.svg'],
      'groundfloor' => ['name' => 'Groundfloor', 'source' => 'local', 'image_name' => 'groundfloor.jpg'],
      'gtm-payroll-services' => ['name' => 'GTM Payroll Services', 'source' => 'local', 'image_name' => 'gtm-payroll-services.jpg'],
      'google' => ['name' => 'Google', 'source' => 'local', 'image_name' => 'google.svg'],
      'google-sheets' => ['name' => 'Google Sheets', 'source' => 'local', 'image_name' => 'google-sheets.png'],
      'hangouts' => ['name' => 'Hangouts', 'source' => 'local', 'image_name' => 'hangouts.svg'],
      'harvest' => ['name' => 'Harvest', 'source' => 'local', 'image_name' => 'harvest.jpg'],
      'heartland' => ['name' => 'Heartland', 'source' => 'local', 'image_name' => 'heartland.svg'],
      'hel-cim' => ['name' => 'Hel Cim', 'source' => 'local', 'image_name' => 'hel-cim.jpg'],
      'hiscox' => ['name' => 'Hiscox', 'source' => 'local', 'image_name' => 'hiscox.svg'],
      'hilton' => ['name' => 'Hilton', 'source' => 'local', 'image_name' => 'hilton.jpg'],
      'hiveage' => ['name' => 'Hiveage', 'source' => 'local', 'image_name' => 'hiveage.png'],
      'homepay' => ['name' => 'Homepay', 'source' => 'local', 'image_name' => 'homepay.jpg'],
      'homeworksolutions' => ['name' => 'Homework Solutions', 'source' => 'local', 'image_name' => 'homeworksolutions.svg'],
      'honeywell' => ['name' => 'Honeywell', 'source' => 'local', 'image_name' => 'honeywell.jpg'],
      'hostwinds' => ['name' => 'Hostwinds', 'source' => 'local', 'image_name' => 'hostwinds.svg'],
      'hover' => ['name' => 'Hover', 'source' => 'local', 'image_name' => 'hover.jpg'],
      'hrblock' => ['name' => 'H&R Block', 'source' => 'local', 'image_name' => 'hrblock.svg'],
      'hr-my' => ['name' => 'HR.my', 'source' => 'local', 'image_name' => 'hr-my.jpg'],
      'hubspot' => ['name' => 'HubSpot', 'source' => 'local', 'image_name' => 'hubspot.svg'],
      'hubstaff' => ['name' => 'Hubstaff', 'source' => 'local', 'image_name' => 'hubstaff.svg'],
      'huntington' => ['name' => 'Huntington', 'source' => 'local', 'image_name' => 'huntington.svg'],
      'ifundwomen' => ['name' => 'iFundWomen', 'source' => 'local', 'image_name' => 'ifundwomen.jpg'],
      'ignite-spot' => ['name' => 'IgniteSpot', 'source' => 'local', 'image_name' => 'ignite-spot.jpg'],
      'incfile' => ['name' => 'Incfile', 'source' => 'local', 'image_name' => 'incfile.jpg'],
      'indeed' => ['name' => 'Indeed', 'source' => 'local', 'image_name' => 'indeed.jpg'],
      'indiegogo' => ['name' => 'Indiegogo', 'source' => 'local', 'image_name' => 'indiegogo.svg'],
      'indinero' => ['name' => 'inDinero', 'source' => 'local', 'image_name' => 'indinero.jpg'],
      'inflow' => ['name' => 'InFlow', 'source' => 'local', 'image_name' => 'inflow.svg'],
      'inmotion-hosting' => ['name' => 'InMotion Hosting', 'source' => 'local', 'image_name' => 'inmotion-hosting.jpg'],
      'inova-payroll' => ['name' => 'Inova Payroll', 'source' => 'local', 'image_name' => 'inova-payroll.jpg'],
      'interactive-brokers' => ['name' => 'Interactive Brokers', 'source' => 'local', 'image_name' => 'interactive-brokers.jpg'],
      'intuit-mint' => ['name' => 'Intuit Mint', 'source' => 'local', 'image_name' => 'intuit-mint.svg'],
      'inventory-now' => ['name' => 'Inventory Now', 'source' => 'local', 'image_name' => 'inventory-now.jpg'],
      'ipage-hosting' => ['name' => 'iPage Hosting', 'source' => 'local', 'image_name' => 'ipage-hosting.jpg'],
      'iwantmyname' => ['name' => 'Iwantmyname', 'source' => 'local', 'image_name' => 'iwantmyname.jpg'],
      'jira' => ['name' => 'Jira', 'source' => 'local', 'image_name' => 'jira.svg'],
      'jive' => ['name' => 'Jive', 'source' => 'local', 'image_name' => 'jive.svg'],
      'jpmorgan-chase-bank-business' => ['name' => 'JP Morgan Chase Bank Business', 'source' => 'local', 'image_name' => 'jpmorgan-chase-bank-business.jpg'],
      'jupiterx' => ['name' => 'Jupiter X', 'source' => 'local', 'image_name' => 'jupiterx.jpg'],
      'justhost' => ['name' => 'Justhost.com', 'source' => 'local', 'image_name' => 'justhost.jpg'],
      'kashoo' => ['name' => 'Kashoo', 'source' => 'local', 'image_name' => 'kashoo.svg'],
      'key-bank' => ['name' => 'Key Bank', 'source' => 'local', 'image_name' => 'keybank.svg'],
      'lending-home' => ['name' => 'Kiavi', 'source' => 'local', 'image_name' => 'kiavi.svg'],
      'kickstarter' => ['name' => 'Kickstarter', 'source' => 'local', 'image_name' => 'kickstarter.svg'],
      'kiva' => ['name' => 'Kiva', 'source' => 'local', 'image_name' => 'kiva.svg'],
      'kpmg-spark' => ['name' => 'KPMG Spark', 'source' => 'local', 'image_name' => 'kpmg-spark.svg'],
      'lavu' => ['name' => 'Lavu', 'source' => 'local', 'image_name' => 'lavu.jpg'],
      'leandomainsearch' => ['name' => 'Lean Domain Search', 'source' => 'local', 'image_name' => 'leandomainsearch.jpg'],
      'lendingone' => ['name' => 'Lending One', 'source' => 'local', 'image_name' => 'lendingone.jpg'],
      'lendr' => ['name' => 'Lendr', 'source' => 'local', 'image_name' => 'lendr.jpg'],
      'less-annoying-crm' => ['name' => 'Less Annoying CRM', 'source' => 'local', 'image_name' => 'less-annoying-crm.svg'],
      'lessonly' => ['name' => 'Lessonly', 'source' => 'local', 'image_name' => 'lessonly.svg'],
      'liberty-tax' => ['name' => 'Liberty Tax', 'source' => 'local', 'image_name' => 'libertytax.svg'],
      'lightstream' => ['name' => 'Light Stream', 'source' => 'local', 'image_name' => 'lightstream.svg'],
      'life-storage' => ['name' => 'Life Storage', 'source' => 'local', 'image_name' => 'life-storage.png'],
      'liquid-web' => ['name' => 'Liquid Web', 'source' => 'local', 'image_name' => 'liquid-web.jpg'],
      'litmos' => ['name' => 'Litmos', 'source' => 'local', 'image_name' => 'litmos.svg'],
      'liveplan' => ['name' => 'LivePlan', 'source' => 'local', 'image_name' => 'liveplan.svg'],
      'loanbuilder-paypal' => ['name' => 'Loanbuilder Paypal', 'source' => 'local', 'image_name' => 'loanbuilder-paypal.jpg'],
      'lorex' => ['name' => 'Lorex', 'source' => 'local', 'image_name' => 'lorex.svg'],
      'lynda' => ['name' => 'Lynda', 'source' => 'local', 'image_name' => 'lynda.svg'],
      'm&t-bank' => ['name' => 'M&T Bank', 'source' => 'local', 'image_name' => 'm&t-bank.svg'],
      'manhattan-wms' => ['name' => 'Manhattan WMS', 'source' => 'local', 'image_name' => 'manhattan-wms.jpg'],
      'marketman' => ['name' => 'MarketMan', 'source' => 'local', 'image_name' => 'marketman.jpg'],
      'marriot' => ['name' => 'Marriot', 'source' => 'local', 'image_name' => 'marriot.jpg'],
      'megapath' => ['name' => 'MegaPath', 'source' => 'local', 'image_name' => 'megapath.jpg'],
      'merrill-lynch' => ['name' => 'Merill Lynch', 'source' => 'local', 'image_name' => 'merrill-lynch.svg'],
      'merritt-bookkeeping' => ['name' => 'Merritt Bookkeeping', 'source' => 'local', 'image_name' => 'merritt-bookkeeping.jpg'],
      'microsoft-office-web-app' => ['name' => 'Microsoft Office Web App', 'source' => 'local', 'image_name' => 'microsoft-office-web-app.jpg'],
      'microsoft-excel' => ['name' => 'Microsoft Excel', 'source' => 'local', 'image_name' => 'microsoft-excel.svg'],
      'microsoft-teams' => ['name' => 'Microsoft Teams', 'source' => 'local', 'image_name' => 'microsoft-teams.svg'],
      'minute7' => ['name' => 'Minute7', 'source' => 'local', 'image_name' => 'minute7.jpg'],
      'money-manager-ex' => ['name' => 'Money Manager Ex', 'source' => 'local', 'image_name' => 'money-manager-ex.jpg'],
      'morweb' => ['name' => 'Morweb', 'source' => 'local', 'image_name' => 'morweb.jpg'],
      'mpower' => ['name' => 'Mpower', 'source' => 'local', 'image_name' => 'mpower.svg'],
      'music-glue' => ['name' => 'Music Glue', 'source' => 'local', 'image_name' => 'music-glue.jpg'],
      'nadamoo' => ['name' => 'Nadamoo', 'source' => 'local', 'image_name' => 'nadamoo.jpg'],
      'name' => ['name' => 'Name.com', 'source' => 'local', 'image_name' => 'name.svg'],
      'namecheap' => ['name' => 'Namecheap', 'source' => 'local', 'image_name' => 'namecheap.svg'],
      'name-mesh' => ['name' => 'Name Mesh', 'source' => 'local', 'image_name' => 'name-mesh.jpg'],
      'namestation' => ['name' => 'Namestation', 'source' => 'local', 'image_name' => 'namestation.jpg'],
      'nannychex' => ['name' => 'NannyChex', 'source' => 'local', 'image_name' => 'nannychex.jpg'],
      'nase' => ['name' => 'Nase', 'source' => 'local', 'image_name' => 'nase.jpg'],
      'national-business-capital' => ['name' => 'National Business Capital', 'source' => 'local', 'image_name' => 'national-business-capital.png'],
      'national-funding' => ['name' => 'National Funding', 'source' => 'local', 'image_name' => 'national-funding.jpg'],
      'national-processing' => ['name' => 'National Processing', 'source' => 'local', 'image_name' => 'national-processing.jpg'],
      'nch-software' => ['name' => 'NCH Software', 'source' => 'local', 'image_name' => 'nch-software.jpg'],
      'neat' => ['name' => 'Neat', 'source' => 'local', 'image_name' => 'neat.jpg'],
      'netsuite' => ['name' => 'Netsuite', 'source' => 'local', 'image_name' => 'netsuite.jpg'],
      'nextiva' => ['name' => 'Nextiva', 'source' => 'local', 'image_name' => 'nextiva.svg'],
      'northone' => ['name' => 'NorthOne', 'source' => 'local', 'image_name' => 'northone.svg'],
      'novo' => ['name' => 'Novo', 'source' => 'local', 'image_name' => 'novo.svg'],
      'nutcache' => ['name' => 'Nutcache', 'source' => 'local', 'image_name' => 'nutcache.png'],
      'odoo' => ['name' => 'Odoo', 'source' => 'local', 'image_name' => 'odoo.png'],
      'oneup' => ['name' => 'One Up', 'source' => 'local', 'image_name' => 'oneup.jpg'],
      'on-shelf' => ['name' => 'On Shelf', 'source' => 'local', 'image_name' => 'on-shelf.jpg'],
      'optinmonster' => ['name' => 'Optin Monster', 'source' => 'local', 'image_name' => 'optinmonster.svg'],
      'oracle' => ['name' => 'Oracle', 'source' => 'local', 'image_name' => 'oracle.svg'],
      'ordoro' => ['name' => 'Ordoro', 'source' => 'local', 'image_name' => 'ordoro.svg'],
      'paloaltonetworks' => ['name' => 'Palo Alto Networks', 'source' => 'local', 'image_name' => 'paloaltonetworks.svg'],
      'panabee' => ['name' => 'Panabee', 'source' => 'local', 'image_name' => 'panabee.jpg'],
      'partkeepr' => ['name' => 'PartKeepr', 'source' => 'local', 'image_name' => 'partkeepr.jpg'],
      'patreon' => ['name' => 'Patreon', 'source' => 'local', 'image_name' => 'patreon.svg'],
      'patriotsoftware' => ['name' => 'Patriot Software', 'source' => 'local', 'image_name' => 'patriotsoftware.svg'],
      'paychex' => ['name' => 'Paychex', 'source' => 'local', 'image_name' => 'paychex.svg'],
      'paycor' => ['name' => 'Paycor', 'source' => 'local', 'image_name' => 'paycor.svg'],
      'payline' => ['name' => 'Payline', 'source' => 'local', 'image_name' => 'payline.jpg'],
      'paymentdepot' => ['name' => 'Payment Depot', 'source' => 'local', 'image_name' => 'paymentdepot.jpg'],
      'paypal-working-capital' => ['name' => 'PayPal Working Capital', 'source' => 'local', 'image_name' => 'paypal-working-capital.jpg'],
      'payroll4free' => ['name' => 'Payroll4Free', 'source' => 'local', 'image_name' => 'payroll4free.jpg'],
      'personal-capital' => ['name' => 'Personal Capital', 'source' => 'local', 'image_name' => 'personal-capital.jpg'],
      'phonedotcom' => ['name' => 'Phone.com', 'source' => 'local', 'image_name' => 'phonedotcom.svg'],
      'pilot' => ['name' => 'Pilot', 'source' => 'local', 'image_name' => 'pilot.jpg'],
      'pipedrive' => ['name' => 'Pipedrive', 'source' => 'local', 'image_name' => 'pipedrive.svg'],
      'pixpa' => ['name' => 'Pixpa', 'source' => 'local', 'image_name' => 'pixpa.svg'],
      'planguru' => ['name' => 'Plan Guru', 'source' => 'local', 'image_name' => 'planguru.png'],
      'pnc' => ['name' => 'PNC', 'source' => 'local', 'image_name' => 'pnc.svg'],
      'pocket' => ['name' => 'Pocket', 'source' => 'local', 'image_name' => 'pocket.png'],
      'poppinspayroll' => ['name' => 'Poppins Payroll', 'source' => 'local', 'image_name' => 'poppinspayroll.jpg'],
      'prosper' => ['name' => 'Prosper', 'source' => 'local', 'image_name' => 'prosper.svg'],
      'quarterspot' => ['name' => 'Quarter Spot', 'source' => 'local', 'image_name' => 'quarterspot.jpg'],
      'quicken' => ['name' => 'Quicken', 'source' => 'local', 'image_name' => 'quicken.svg'],
      'quick-base' => ['name' => 'Quick Base', 'source' => 'local', 'image_name' => 'quick-base.svg'],
      'quickspot' => ['name' => 'Quickspot', 'source' => 'local', 'image_name' => 'quickspot.jpg'],
      'really-simple-systems' => ['name' => 'Really Simple Systems', 'source' => 'local', 'image_name' => 'really-simple-systems.png'],
      'residential-capital-partners' => ['name' => 'Residential Capital Partners', 'source' => 'local', 'image_name' => 'residential-capital-partners.jpg'],
      'revel' => ['name' => 'Revel', 'source' => 'local', 'image_name' => 'revel.svg'],
      'rightcontrol' => ['name' => 'Right Control', 'source' => 'local', 'image_name' => 'rightcontrol.jpg'],
      'rocketloans' => ['name' => 'Rocket Loans', 'source' => 'local', 'image_name' => 'rocketloans.jpg'],
      'safestreets' => ['name' => 'SafeStreets', 'source' => 'local', 'image_name' => 'safestreets.svg'],
      'salesforce' => ['name' => 'Salesforce', 'source' => 'local', 'image_name' => 'salesforce.svg'],
      'santander' => ['name' => 'Santander', 'source' => 'local', 'image_name' => 'santander.jpg'],
      'savvynanny' => ['name' => 'Savvy Nanny', 'source' => 'local', 'image_name' => 'savvynanny.jpg'],
      'seedinvest' => ['name' => 'Seed Invest', 'source' => 'local', 'image_name' => 'seedinvest.svg'],
      'sharedcount' => ['name' => 'Shared Count', 'source' => 'local', 'image_name' => 'sharedcount.svg'],
      'shoeboxed' => ['name' => 'Shoeboxed', 'source' => 'local', 'image_name' => 'shoeboxed.svg'],
      'shopify' => ['name' => 'Shopify', 'source' => 'local', 'image_name' => 'shopify.svg'],
      'shopkeep' => ['name' => 'Shopkeep', 'source' => 'local', 'image_name' => 'shopkeep.svg'],
      'simplebank' => ['name' => 'Simple', 'source' => 'local', 'image_name' => 'simplebank.jpg'],
      'simplenanny' => ['name' => 'Simple Nanny', 'source' => 'local', 'image_name' => 'simplenanny.jpg'],
      'simplilearn' => ['name' => 'Simplilearn', 'source' => 'local', 'image_name' => 'simplilearn.svg'],
      'siteground' => ['name' => 'Siteground', 'source' => 'local', 'image_name' => 'siteground.jpg'],
      'skillsoft' => ['name' => 'Skillsoft', 'source' => 'local', 'image_name' => 'skillsoft.svg'],
      'slickpie' => ['name' => 'Slick Pie', 'source' => 'local', 'image_name' => 'slickpie.jpg'],
      'small-business-bank' => ['name' => 'Small Business Bank', 'source' => 'local', 'image_name' => 'smallbusinessbank.png'],
      'smart-receipts' => ['name' => 'Smart Receipts', 'source' => 'local', 'image_name' => 'smart-receipts.jpg'],
      'smugmug' => ['name' => 'SmugMug', 'source' => 'local', 'image_name' => 'smugmug.jpg'],
      'snapcap' => ['name' => 'Snap Cap', 'source' => 'local', 'image_name' => 'snapcap.jpg'],
      'sonicwall' => ['name' => 'Sonicwall', 'source' => 'local', 'image_name' => 'sonicwall.svg'],
      'sophos' => ['name' => 'Sophos', 'source' => 'local', 'image_name' => 'sophos.svg'],
      'sortly' => ['name' => 'Sortly', 'source' => 'local', 'image_name' => 'sortly.jpg'],
      'sprint-tmobile' => ['name' => 'Sprint T-Mobile', 'source' => 'local', 'image_name' => 'sprint-tmobile.svg'],
      'stitchlabs' => ['name' => 'Stitch Labs', 'source' => 'local', 'image_name' => 'stitchlabs.jpg'],
      'straighttalk' => ['name' => 'Straight Talk', 'source' => 'local', 'image_name' => 'straighttalk.jpg'],
      'stratpad' => ['name' => 'StratPad', 'source' => 'local', 'image_name' => 'stratpad.jpg'],
      'stockcontrol' => ['name' => 'Stock Control', 'source' => 'local', 'image_name' => 'stockcontrol.jpg'],
      'streetshares' => ['name' => 'Street Shares', 'source' => 'local', 'image_name' => 'streetshares.png'],
      'suntrust-truist' => ['name' => 'Suntrust now Truist', 'source' => 'local', 'image_name' => 'suntrust-truist.svg'],
      'suracy' => ['name' => 'Suracy', 'source' => 'local', 'image_name' => 'suracy.jpg'],
      'talent-lms' => ['name' => 'Talent LMS', 'source' => 'local', 'image_name' => 'talent-lms.svg'],
      'taotronics' => ['name' => 'Taotronics', 'source' => 'local', 'image_name' => 'taotronics.jpg'],
      'taxact' => ['name' => 'Tax Act', 'source' => 'local', 'image_name' => 'taxact.jpg'],
      'tdameritrade' => ['name' => 'TD Ameritrade', 'source' => 'local', 'image_name' => 'tdameritrade.svg'],
      'td-bank' => ['name' => 'TD Bank', 'source' => 'local', 'image_name' => 'td-bank.jpg'],
      't-mobilebusiness' => ['name' => 'T-Mobile for Business', 'source' => 'local', 'image_name' => 't-mobilebusiness.svg'],
      'teltik' => ['name' => 'Teltik', 'source' => 'local', 'image_name' => 'teltik.jpg'],
      'teramind' => ['name' => 'Teramind', 'source' => 'local', 'image_name' => 'teramind.jpg'],
      'themeforest' => ['name' => 'ThemeForest', 'source' => 'local', 'image_name' => 'themeforest.jpg'],
      'themegrill' => ['name' => 'Theme Grill', 'source' => 'local', 'image_name' => 'themegrill.jpg'],
      'themeisle' => ['name' => 'Theme Isle', 'source' => 'local', 'image_name' => 'themeisle.jpg'],
      'timecamp' => ['name' => 'Timecamp', 'source' => 'local', 'image_name' => 'timecamp.jpg'],
      'timetrex' => ['name' => 'TimeTrex', 'source' => 'local', 'image_name' => 'timetrex.jpg'],
      'tipalti' => ['name' => 'Tipalti', 'source' => 'local', 'image_name' => 'tipalti.jpg'],
      'tmd-hosting' => ['name' => 'TMD Hosting', 'source' => 'local', 'image_name' => 'tmd-hosting.jpg'],
      'toast' => ['name' => 'Toast', 'source' => 'local', 'image_name' => 'toast.jpg'],
      'toggl' => ['name' => 'Toggl', 'source' => 'local', 'image_name' => 'toggl.jpg'],
      'toryburch' => ['name' => 'Toryburch', 'source' => 'local', 'image_name' => 'toryburch.png'],
      'touchbistro' => ['name' => 'Touch Bistro', 'source' => 'local', 'image_name' => 'touchbistro.jpg'],
      'tradestation' => ['name' => 'Trade Station', 'source' => 'local', 'image_name' => 'tradestation.jpg'],
      'travelers' => ['name' => 'Travelers', 'source' => 'local', 'image_name' => 'travelers.svg'],
      'trello' => ['name' => 'Trello', 'source' => 'local', 'image_name' => 'trello.jpg'],
      'trigger' => ['name' => 'Trigger', 'source' => 'local', 'image_name' => 'trigger.svg'],
      'triumph-business-capital' => ['name' => 'Triumph Business Capital', 'source' => 'local', 'image_name' => 'triumph-business-capital.jpg'],
      'tsys' => ['name' => 'TSYS', 'source' => 'local', 'image_name' => 'tsys.jpg'],
      'turbocash' => ['name' => 'Turbo Cash', 'source' => 'local', 'image_name' => 'turbocash.jpg'],
      'unleashed' => ['name' => 'Unleashed', 'source' => 'local', 'image_name' => 'unleashed.svg'],
      'upserve' => ['name' => 'Upserve', 'source' => 'local', 'image_name' => 'upserve.svg'],
      'upstart' => ['name' => 'Upstart', 'source' => 'local', 'image_name' => 'upstart.jpg'],
      'usbank' => ['name' => 'US Bank', 'source' => 'local', 'image_name' => 'usbank.svg'],
      'veeqo' => ['name' => 'Veeqo', 'source' => 'local', 'image_name' => 'veeqo.svg'],
      'vend' => ['name' => 'Vend', 'source' => 'local', 'image_name' => 'vend.svg'],
      'vericlock' => ['name' => 'VeriClock', 'source' => 'local', 'image_name' => 'vericlock.jpg'],
      'veryfi' => ['name' => 'Veryfi', 'source' => 'local', 'image_name' => 'veryfi.jpg'],
      'wagepoint' => ['name' => 'Wagepoint', 'source' => 'local', 'image_name' => 'wagepoint.svg'],
      'wally' => ['name' => 'Wally', 'source' => 'local', 'image_name' => 'wally.jpg'],
      'watchguard' => ['name' => 'Watch Guard', 'source' => 'local', 'image_name' => 'watchguard.jpg'],
      'wells-fargo' => ['name' => 'Wells Fargo', 'source' => 'local', 'image_name' => 'wells-fargo.svg'],
      'womensnet' => ['name' => 'Womens Net', 'source' => 'local', 'image_name' => 'womensnet.jpg'],
      'wonenice' => ['name' => 'Wone Nice', 'source' => 'local', 'image_name' => 'wonenice.jpg'],
      'woocommerce' => ['name' => 'WooCommerce', 'source' => 'local', 'image_name' => 'woocommerce.jpg'],
      'wordlab' => ['name' => 'Wordlab', 'source' => 'local', 'image_name' => 'wordlab.jpg'],
      'workbright' => ['name' => 'Workbright', 'source' => 'local', 'image_name' => 'workbright.svg'],
      'workflow' => ['name' => 'Workflow', 'source' => 'local', 'image_name' => 'workflow.svg'],
      'wp-engine' => ['name' => 'WP Engine', 'source' => 'local', 'image_name' => 'wp-engine.jpg'],
      'wrike' => ['name' => 'Wrike', 'source' => 'local', 'image_name' => 'wrike.jpg'],
      'yahoo-finance' => ['name' => 'Yahoo Finance', 'source' => 'local', 'image_name' => 'yahoo-finance.svg'],
      'ynab' => ['name' => 'YNAB', 'source' => 'local', 'image_name' => 'ynab.jpg'],
      'yoast' => ['name' => 'Yoast', 'source' => 'local', 'image_name' => 'yoast.svg'],
      'zackstrade' => ['name' => 'Zacks Trade', 'source' => 'local', 'image_name' => 'zackstrade.jpg'],
      'zebra' => ['name' => 'Zebra', 'source' => 'local', 'image_name' => 'zebra.jpg'],
      'zenefits' => ['name' => 'Zenefits', 'source' => 'local', 'image_name' => 'zenefits.svg'],
      'zipbooks' => ['name' => 'ZipBooks', 'source' => 'local', 'image_name' => 'zipbooks.svg'],
      'zoom' => ['name' => 'Zoom', 'source' => 'local', 'image_name' => 'zoom.svg'],
      'zosi' => ['name' => 'Zosi', 'source' => 'local', 'image_name' => 'zosi.jpg'],
      'zscaler' => ['name' => 'Zscaler', 'source' => 'local', 'image_name' => 'zscaler.jpg'],
      'zurich' => ['name' => 'Zurich', 'source' => 'local', 'image_name' => 'zurich.png'],
      'frontpoint' => ['name' => 'Frontpoint', 'source' => 'local', 'image_name' => 'frontpoint.svg', 'redb' => 'frontpoint-logo'],
      'vivint' => ['name' => 'Vivint', 'source' => 'local', 'image_name' => 'vivint.svg', 'redb' => 'vivint-logo'],
      'scout' => ['name' => 'Scout', 'source' => 'local', 'image_name' => 'scout.png', 'redb' => 'scout-logo'],
      'simplisafe' => ['name' => 'SimpliSafe', 'source' => 'local', 'image_name' => 'simplisafe.svg', 'redb' => 'simplisafe-logo'],
      'livewatch' => ['name' => 'Livewatch', 'source' => 'local', 'image_name' => 'livewatch.png'],
      'monitronics' => ['name' => 'Monitronics', 'source' => 'local', 'image_name' => ''],
      'armorax' => ['name' => 'Armorax', 'source' => 'local', 'image_name' => 'armorax.png'],
      'astound-digital-west' => ['name' => 'Astound Digital West', 'source' => 'local', 'image_name' => 'astound-digital-west.svg'],
      'astound-entouch' => ['name' => 'Astound Entouch', 'source' => 'local', 'image_name' => 'astound-entouch.svg'],
      'astound-grande' => ['name' => 'Astound Grande', 'source' => 'local', 'image_name' => 'astound-grande.svg', 'redb' => 'grande-cable-logo'],
      'astound-rcn' => ['name' => 'Astound RCN', 'source' => 'local', 'image_name' => 'astound-rcn.svg', 'redb' => 'rcn-logo'],
      'astound-wave' => ['name' => 'Astound Wave ', 'source' => 'local', 'image_name' => 'astound-wave.svg'],
      'adt' => ['name' => 'ADT', 'source' => 'local', 'image_name' => 'safestreets.svg'],
      'adt-logo' => ['name' => 'ADT Logo', 'source' => 'local', 'image_name' => 'adt.svg', 'redb' => 'adt-logo'],
      'adt-command' => ['name' => 'ADT Command', 'source' => 'local', 'image_name' => 'adt-command.svg', 'redb' => 'adt-command-logo'],
      'adt-pulse' => ['name' => 'ADT Pulse Logo', 'source' => 'local', 'image_name' => 'adt-pulse.svg', 'redb' => 'adt-pulse-logo'],
      'adt-shield' => ['name' => 'ADT Shield', 'source' => 'local', 'image_name' => 'adt-shield.svg'],
      'att-digital' => ['name' => 'AT&T Digital', 'source' => 'local', 'image_name' => 'att-digital.png'],
      'alarmforce' => ['name' => 'Alarm Force', 'source' => 'local', 'image_name' => 'alarmforce.png'],
      'alert1' => ['name' => 'Alert1', 'source' => 'local', 'image_name' => 'alert1.png'],
      'bay-alarm' => ['name' => 'Bay Alarm', 'source' => 'local', 'image_name' => 'bay-alarm.svg'],
      'lifefone' => ['name' => 'Lifefone', 'source' => 'local', 'image_name' => 'lifefone.png'],
      'medical-guardian' => ['name' => 'Medical Guardian', 'source' => 'local', 'image_name' => 'medical-guardian.png'],
      'credit-sesame' => ['name' => 'Credit Sesame', 'source' => 'local', 'image_name' => 'credit-sesame.svg'],
      'equifax' => ['name' => 'Equifax', 'source' => 'local', 'image_name' => 'equifax.png'],
      'experian' => ['name' => 'Experian', 'source' => 'local', 'image_name' => 'experian.png'],
      'identityforce' => ['name' => 'IdentityForce', 'source' => 'local', 'image_name' => 'identityforce.png'],
      'identity-guard' => ['name' => 'Identity Guard', 'source' => 'local', 'image_name' => 'identity-guard.svg'],
      'lifelock' => ['name' => 'LifeLock', 'source' => 'local', 'image_name' => 'lifelock.png'],
      'myfico' => ['name' => 'myFICO', 'source' => 'local', 'image_name' => 'myfico.png'],
      'privacy-guard' => ['name' => 'Privacy Guard', 'source' => 'local', 'image_name' => 'privacy-guard.png'],
      'transunion' => ['name' => 'TransUnion', 'source' => 'local', 'image_name' => 'transunion.png'],
      'credit-karma' => ['name' => 'Credit Karma', 'source' => 'local', 'image_name' => 'credit-karma.png'],
      'myidcare' => ['name' => 'MyIDCare', 'source' => 'local', 'image_name' => 'myidcare.png'],
      'protectmyid' => ['name' => 'ProtectMyID', 'source' => 'local', 'image_name' => 'protectmyid.png'],
      'zander' => ['name' => 'Zander', 'source' => 'local', 'image_name' => 'zander.png'],
      'nest' => ['name' => 'Nest', 'source' => 'local', 'image_name' => 'nest.svg'],
      'nest-secure' => ['name' => 'Nest Secure', 'source' => 'local', 'image_name' => 'nest-secure.svg', 'redb' => 'nest-secure-logo'],
      'cove' => ['name' => 'Cove', 'source' => 'local', 'image_name' => 'cove.svg', 'redb' => 'cove-logo'],
      'abode' => ['name' => 'Abode', 'source' => 'local', 'image_name' => 'abode.png', 'redb' => 'abode-logo'],
      'abode-horizontal' => ['name' => 'Abode Horizontal', 'source' => 'local', 'image_name' => 'abode-horizontal.png'],
      'brinks-home-security' => ['name' => 'Brinks Home Security', 'source' => 'local', 'image_name' => 'brinks-logo.png', 'redb' => 'brinks-logo'],
      'ring' => ['name' => 'Ring', 'source' => 'local', 'image_name' => 'ring.png', 'redb' => 'ring-logo'],
      'get-safe' => ['name' => 'Get Safe', 'source' => 'local', 'image_name' => 'get-safe.svg', 'redb' => 'get-safe-logo'],
      'identity-iq' => ['name' => 'Identity IQ', 'source' => 'local', 'image_name' => 'identity-iq.png'],
      'lendio' => ['name' => 'Lendio', 'source' => 'local', 'image_name' => 'lendio.svg'],
      'fundera' => ['name' => 'Fundera', 'source' => 'local', 'image_name' => 'fundera.svg'],
      'aetna-coventry' => ['name' => 'Aetn Coventry', 'source' => 'local', 'image_name' => 'aetna-coventry.png'],
      'anthem' => ['name' => 'Anthem', 'source' => 'local', 'image_name' => 'anthem.png'],
      'bluecross-blueshield' => ['name' => 'BlueCross BlueShield', 'source' => 'local', 'image_name' => 'bluecross-blueshield.png'],
      'cigna' => ['name' => 'Cigna', 'source' => 'local', 'image_name' => 'cigna.png'],
      'humana' => ['name' => 'Humana', 'source' => 'local', 'image_name' => 'humana.png'],
      'kaiser-permanente' => ['name' => 'Kaiser Permanente', 'source' => 'local', 'image_name' => 'kaiser-permanente.png'],
      'regence' => ['name' => 'Regence', 'source' => 'local', 'image_name' => 'regence.png'],
      'silverscript' => ['name' => 'SilverScript', 'source' => 'local', 'image_name' => 'silverscript.png'],
      'united-healthcare' => ['name' => 'UnitedHealthcare', 'source' => 'local', 'image_name' => 'united-healthcare.png'],
      'wellcare' => ['name' => 'WellCare', 'source' => 'local', 'image_name' => 'wellcare.png'],
      '5star-life' => ['name' => '5star Life', 'source' => 'local', 'image_name' => '5star-life.png'],
      'aaa' => ['name' => 'AAA', 'source' => 'local', 'image_name' => 'aaa.png'],
      'aarp' => ['name' => 'AARP', 'source' => 'local', 'image_name' => 'aarp.png'],
      'aicpa' => ['name' => 'AICPA', 'source' => 'local', 'image_name' => 'aicpa.png'],
      'aig' => ['name' => 'AIG', 'source' => 'local', 'image_name' => 'aig.png'],
      'axa-equitable' => ['name' => 'AXA Equitable', 'source' => 'local', 'image_name' => 'axa-equitable.png'],
      'accion' => ['name' => 'Accion', 'source' => 'local', 'image_name' => 'accion.svg'],
      'accordia' => ['name' => 'Accordia', 'source' => 'local', 'image_name' => 'accordia.png'],
      'aegon' => ['name' => 'Aegon', 'source' => 'local', 'image_name' => 'aegon.png'],
      'aetna' => ['name' => 'Aetna', 'source' => 'local', 'image_name' => 'aetna.png'],
      'aflac' => ['name' => 'Aflac', 'source' => 'local', 'image_name' => 'aflac.png'],
      'allianz' => ['name' => 'Allianz', 'source' => 'local', 'image_name' => 'allianz.png'],
      'allstate' => ['name' => 'Allstate', 'source' => 'local', 'image_name' => 'allstate.png'],
      'american-amicable' => ['name' => 'American Amicable', 'source' => 'local', 'image_name' => 'american-amicable.png'],
      'american-equity' => ['name' => 'American Equity', 'source' => 'local', 'image_name' => 'american-equity.png'],
      'american-family' => ['name' => 'American Family', 'source' => 'local', 'image_name' => 'american-family.png'],
      'american-fidelity' => ['name' => 'American Fidelity', 'source' => 'local', 'image_name' => 'american-fidelity.png'],
      'american-general' => ['name' => 'American General', 'source' => 'local', 'image_name' => 'american-general.png'],
      'american-memorial' => ['name' => 'American Memorial', 'source' => 'local', 'image_name' => 'american-memorial.png'],
      'american-national' => ['name' => 'American National', 'source' => 'local', 'image_name' => 'american-national.png'],
      'american-united-one-america' => ['name' => 'American United One America', 'source' => 'local', 'image_name' => 'american-united-one-america.png'],
      'americo' => ['name' => 'Americo', 'source' => 'local', 'image_name' => 'americo.png'],
      'ameritas' => ['name' => 'Ameritas', 'source' => 'local', 'image_name' => 'ameritas.png'],
      'assurity' => ['name' => 'Assurity', 'source' => 'local', 'image_name' => 'assurity.png'],
      'axos' => ['name' => 'Axos', 'source' => 'local', 'image_name' => 'axos.svg'],
      'bankers-life_casuality' => ['name' => 'Bankers Life Casuality', 'source' => 'local', 'image_name' => 'bankers-life_casuality.png'],
      'bank-of-america' => ['name' => 'Bank of America', 'source' => 'local', 'image_name' => 'bank-of-america.svg'],
      'banner-life' => ['name' => 'Banner Life', 'source' => 'local', 'image_name' => 'banner-life.png'],
      'bestow' => ['name' => 'Bestow', 'source' => 'local', 'image_name' => 'bestow.png'],
      'big-commerce' => ['name' => 'Big Commerce', 'source' => 'local', 'image_name' => 'big-commerce.svg'],
      'biz-filings' => ['name' => 'Biz Filings', 'source' => 'local', 'image_name' => 'biz-filings.svg'],
      'bookkeeper' => ['name' => 'Book Keeper', 'source' => 'local', 'image_name' => 'bookkeeper.png'],
      'bookkeeper360' => ['name' => 'Book Keeper 360', 'source' => 'local', 'image_name' => 'bookkeeper360.svg'],
      'boston-mutual' => ['name' => 'Boston Mutual', 'source' => 'local', 'image_name' => 'boston-mutual.png'],
      'breeze' => ['name' => 'Breeze', 'source' => 'local', 'image_name' => 'breeze.png'],
      'brighthouse-financial' => ['name' => 'Brighthouse Financial', 'source' => 'local', 'image_name' => 'brighthouse-financial.png'],
      'cin7' => ['name' => 'Cin7', 'source' => 'local', 'image_name' => 'cin7.svg'],
      'cno-financial-group' => ['name' => 'CNO Financial Group', 'source' => 'local', 'image_name' => 'cno-financial-group.png'],
      'cuna-mutual' => ['name' => 'CUNA Mutual', 'source' => 'local', 'image_name' => 'cuna-mutual.png'],
      'cincinnati-insurance' => ['name' => 'Cincinnati Insurance', 'source' => 'local', 'image_name' => 'cincinnati-insurance.png'],
      'colonial-life' => ['name' => 'Colonial Life', 'source' => 'local', 'image_name' => 'colonial-life.png'],
      'colonial-penn' => ['name' => 'Colonial Penn', 'source' => 'local', 'image_name' => 'colonial-penn.png'],
      'columbian-mutual' => ['name' => 'Columbian Mutual', 'source' => 'local', 'image_name' => 'columbian-mutual.png'],
      'columbus-life' => ['name' => 'Columbus Life', 'source' => 'local', 'image_name' => 'columbus-life.png'],
      'combined-insurance' => ['name' => 'Combined Insurance', 'source' => 'local', 'image_name' => 'combined-insurance.png'],
      'costco-life-insurance' => ['name' => 'Costco Life Insurance', 'source' => 'local', 'image_name' => 'costco-life-insurance.png'],
      'delware-life' => ['name' => 'Delware-Life', 'source' => 'local', 'image_name' => 'delware-life.png'],
      'emc-national-life' => ['name' => 'EMC National Life', 'source' => 'local', 'image_name' => 'emc-national-life.png'],
      'equitrust' => ['name' => 'Equitrust', 'source' => 'local', 'image_name' => 'equitrust.png'],
      'erie-insurance' => ['name' => 'Erie Insurance', 'source' => 'local', 'image_name' => 'erie-insurance.png'],
      'farm-bureau' => ['name' => 'Farm Bureau', 'source' => 'local', 'image_name' => 'farm-bureau.png'],
      'farmers' => ['name' => 'Farmers', 'source' => 'local', 'image_name' => 'farmers.png'],
      'fidelity-security' => ['name' => 'Fidelity Security', 'source' => 'local', 'image_name' => 'fidelity-security.png'],
      'fidelity-life-association' => ['name' => 'Fidelity Life Association', 'source' => 'local', 'image_name' => 'fidelity-life-association.png'],
      'finance-power-tools' => ['name' => 'Business Power Tools', 'source' => 'local', 'image_name' => 'finance-power-tools.png'],
      'foresters' => ['name' => 'Foresters', 'source' => 'local', 'image_name' => 'foresters.png'],
      'forethought' => ['name' => 'Forethought', 'source' => 'local', 'image_name' => 'forethought.png'],
      'fresh-books' => ['name' => 'Fresh Books', 'source' => 'local', 'image_name' => 'fresh-books.svg'],
      'fundbox' => ['name' => 'Fundbox', 'source' => 'local', 'image_name' => 'fundbox.svg'],
      'funding-circle' => ['name' => 'Funding Circle', 'source' => 'local', 'image_name' => 'funding-circle.svg'],
      'geico' => ['name' => 'Geico', 'source' => 'local', 'image_name' => 'geico.png'],
      'genworth' => ['name' => 'Genworth', 'source' => 'local', 'image_name' => 'genworth.png'],
      'gerber' => ['name' => 'Gerber', 'source' => 'local', 'image_name' => 'gerber.png'],
      'globe' => ['name' => 'Globe', 'source' => 'local', 'image_name' => 'globe.png'],
      'godaddy' => ['name' => 'GoDaddy', 'source' => 'local', 'image_name' => 'godaddy.svg'],
      'go-small-biz' => ['name' => 'GoSmallBiz', 'source' => 'local', 'image_name' => 'go-small-biz.svg'],
      'grasshopper' => ['name' => 'Grasshopper', 'source' => 'local', 'image_name' => 'grasshopper.png'],
      'great-american' => ['name' => 'Great American', 'source' => 'local', 'image_name' => 'great-american.png'],
      'guardian-life' => ['name' => 'Guardian Life', 'source' => 'local', 'image_name' => 'guardian-life.png'],
      'gusto' => ['name' => 'Gusto', 'source' => 'local', 'image_name' => 'gusto.svg'],
      'hartford' => ['name' => 'Hartford', 'source' => 'local', 'image_name' => 'hartford.png'],
      'haven-life' => ['name' => 'Haven Life', 'source' => 'local', 'image_name' => 'haven-life.png'],
      'horace-mann' => ['name' => 'Horace rMann', 'source' => 'local', 'image_name' => 'horace-mann.png'],
      'hostgator' => ['name' => 'HostGator', 'source' => 'local', 'image_name' => 'hostgator.png'],
      'illinois-mutual' => ['name' => 'Illinois Mutual', 'source' => 'local', 'image_name' => 'illinois-mutual.png'],
      'investors-heritage' => ['name' => 'Investors Heritage', 'source' => 'local', 'image_name' => 'investors-heritage.png'],
      'jackson-national' => ['name' => 'Jackson National', 'source' => 'local', 'image_name' => 'jackson-national.png'],
      'john-hancock' => ['name' => 'John Hancock', 'source' => 'local', 'image_name' => 'john-hancock.png'],
      'kabbage' => ['name' => 'Kabbage', 'source' => 'local', 'image_name' => 'kabbage.svg'],
      'kansas-city-life' => ['name' => 'Kansas City Life', 'source' => 'local', 'image_name' => 'kansas-city-life.png'],
      'kemper' => ['name' => 'Kemper', 'source' => 'local', 'image_name' => 'kemper.png'],
      'knights-of-columbus' => ['name' => 'Knights of Columbus', 'source' => 'local', 'image_name' => 'knights-of-columbus.png'],
      'ladder-life' => ['name' => 'Ladder Life', 'source' => 'local', 'image_name' => 'ladder-life.png'],
      'lafayette-life' => ['name' => 'Lafayette Life', 'source' => 'local', 'image_name' => 'lafayette-life.png'],
      'liberty-mutual' => ['name' => 'Liberty Mutual', 'source' => 'local', 'image_name' => 'liberty-mutual.png'],
      'liberty-bankers' => ['name' => 'Liberty Bankers', 'source' => 'local', 'image_name' => 'liberty-bankers.png'],
      'life-insurance-company-of-alabama' => ['name' => 'Life Insurance Company of Alabama', 'source' => 'local', 'image_name' => 'life-insurance-company-of-alabama.png'],
      'lincoln-national' => ['name' => 'Lincoln National', 'source' => 'local', 'image_name' => 'lincoln-national.png'],
      'lincoln-heritage' => ['name' => 'Lincoln Heritage', 'source' => 'local', 'image_name' => 'lincoln-heritage.png'],
      'lendingclub' => ['name' => 'LendingClub', 'source' => 'local', 'image_name' => 'lendingclub.svg'],
      'madison-national' => ['name' => 'Madison National', 'source' => 'local', 'image_name' => 'madison-national.png'],
      'massmutual' => ['name' => 'MassMutual', 'source' => 'local', 'image_name' => 'massmutual.png'],
      'mcafee' => ['name' => 'McAfee', 'source' => 'local', 'image_name' => 'mcafee.svg'],
      'metlife' => ['name' => 'MetLife', 'source' => 'local', 'image_name' => 'metlife.png'],
      'midland-national' => ['name' => 'Midland National', 'source' => 'local', 'image_name' => 'midland-national.png'],
      'minnesota-life-securian' => ['name' => 'Minnesota Life Securian', 'source' => 'local', 'image_name' => 'minnesota-life-securian.png'],
      'motorists-life' => ['name' => 'Motorists Life', 'source' => 'local', 'image_name' => 'motorists-life.png'],
      'mutual-trust' => ['name' => 'Mutual Trust', 'source' => 'local', 'image_name' => 'mutual-trust.png'],
      'mutual-of-omaha' => ['name' => 'Mutual of Omaha', 'source' => 'local', 'image_name' => 'mutual-of-omaha.png'],
      'national-guard' => ['name' => 'National Guard', 'source' => 'local', 'image_name' => 'national-guard.png'],
      'national-life-group' => ['name' => 'National Life Group', 'source' => 'local', 'image_name' => 'national-life-group.png'],
      'nationwide' => ['name' => 'Nationwide', 'source' => 'local', 'image_name' => 'nationwide.png'],
      'nav' => ['name' => 'Nav', 'source' => 'local', 'image_name' => 'nav.svg'],
      'navy-mutual' => ['name' => 'Navy Mutual', 'source' => 'local', 'image_name' => 'navy-mutual.png'],
      'new-era' => ['name' => 'New Era', 'source' => 'local', 'image_name' => 'new-era.png'],
      'new-york-life' => ['name' => 'New York Life', 'source' => 'local', 'image_name' => 'new-york-life.png'],
      'north-american-company' => ['name' => 'North American Company', 'source' => 'local', 'image_name' => 'north-american-company.png'],
      'northwestern-mutual' => ['name' => 'Northwestern Mutual', 'source' => 'local', 'image_name' => 'northwestern-mutual.png'],
      'norton' => ['name' => 'Norton', 'source' => 'local', 'image_name' => 'norton.svg'],
      'ohio-national' => ['name' => 'Ohio National', 'source' => 'local', 'image_name' => 'ohio-national.png'],
      'ondeck' => ['name' => 'OnDeck', 'source' => 'local', 'image_name' => 'ondeck.svg'],
      'onpay' => ['name' => 'OnPay', 'source' => 'local', 'image_name' => 'onpay.svg'],
      'ooma' => ['name' => 'Ooma', 'source' => 'local', 'image_name' => 'ooma.svg'],
      'oxford-life' => ['name' => 'Oxford Life', 'source' => 'local', 'image_name' => 'oxford-life.png'],
      'pacific-life' => ['name' => 'Pacific Life', 'source' => 'local', 'image_name' => 'pacific-life.png'],
      'pan-american-life' => ['name' => 'Pan American Life', 'source' => 'local', 'image_name' => 'pan-american-life.png'],
      'penn-mutual' => ['name' => 'Penn Mutual', 'source' => 'local', 'image_name' => 'penn-mutual.png'],
      'petersen-international-underwriting' => ['name' => 'Petersen International Underwriting', 'source' => 'local', 'image_name' => 'petersen-international-underwriting.png'],
      'phoenix-life-a-nassau-re' => ['name' => 'Phoenix Life A Nassau Re', 'source' => 'local', 'image_name' => 'phoenix-life-a-nassau-re.png'],
      'physician-mutual' => ['name' => 'Physician Mutual', 'source' => 'local', 'image_name' => 'physician-mutual.png'],
      'policygenius' => ['name' => 'Policygenius', 'source' => 'local', 'image_name' => 'policygenius.png'],
      'primerica' => ['name' => 'Primerica', 'source' => 'local', 'image_name' => 'primerica.png'],
      'principal' => ['name' => 'Principal', 'source' => 'local', 'image_name' => 'principal.png'],
      'privado-vpn' => ['name' => 'Privado VPN', 'source' => 'local', 'image_name' => 'privado-vpn.svg'],
      'progressive' => ['name' => 'Progressive', 'source' => 'local', 'image_name' => 'progressive.png'],
      'protective' => ['name' => 'Protective', 'source' => 'local', 'image_name' => 'protective.png'],
      'prudential' => ['name' => 'Prudential', 'source' => 'local', 'image_name' => 'prudential.png'],
      'quickbooks' => ['name' => 'Quickbooks', 'source' => 'local', 'image_name' => 'quickbooks.svg'],
      'reliance-standard' => ['name' => 'Reliance Standard', 'source' => 'local', 'image_name' => 'reliance-standard.png'],
      'ring-central' => ['name' => 'Ring Central', 'source' => 'local', 'image_name' => 'ring-central.svg'],
      'riversource-life' => ['name' => 'Riversource Life', 'source' => 'local', 'image_name' => 'riversource-life.png'],
      'royal-neighbors-of-america' => ['name' => 'Royal Neighbors of America', 'source' => 'local', 'image_name' => 'royal-neighbors-of-america.png'],
      'sage' => ['name' => 'Sage', 'source' => 'local', 'image_name' => 'sage.svg'],
      'sba' => ['name' => 'SBA', 'source' => 'local', 'image_name' => 'sba.svg'],
      'sbli' => ['name' => 'SBLI', 'source' => 'local', 'image_name' => 'sbli.png'],
      'sagicor' => ['name' => 'Sagicor', 'source' => 'local', 'image_name' => 'sagicor.png'],
      'security-mutual' => ['name' => 'Security Mutual', 'source' => 'local', 'image_name' => 'security-mutual.png'],
      'security-national' => ['name' => 'Security National', 'source' => 'local', 'image_name' => 'security-national.png'],
      'selectquote' => ['name' => 'Selectquote', 'source' => 'local', 'image_name' => 'selectquote.png'],
      'senior-life' => ['name' => 'Senior Life', 'source' => 'local', 'image_name' => 'senior-life.png'],
      'sentinel-security-life' => ['name' => 'Sentinel Security Life', 'source' => 'local', 'image_name' => 'sentinel-security-life.png'],
      'settlers-life' => ['name' => 'Settlers Life', 'source' => 'local', 'image_name' => 'settlers-life.png'],
      'shelter' => ['name' => 'Shelter', 'source' => 'local', 'image_name' => 'shelter.png'],
      'smartbiz' => ['name' => 'SmartBiz', 'source' => 'local', 'image_name' => 'smartbiz.svg'],
      'square' => ['name' => 'Square', 'source' => 'local', 'image_name' => 'square.svg'],
      'squarespace' => ['name' => 'SquareSpace', 'source' => 'local', 'image_name' => 'squarespace.svg'],
      'standard-life_casualty' => ['name' => 'Standard Life_Casualty', 'source' => 'local', 'image_name' => 'standard-life_casualty.png'],
      'starmount' => ['name' => 'Starmount', 'source' => 'local', 'image_name' => 'starmount.png'],
      'state-farm' => ['name' => 'State Farm', 'source' => 'local', 'image_name' => 'state-farm.png'],
      'stripe' => ['name' => 'Stripe', 'source' => 'local', 'image_name' => 'stripe.svg'],
      'sun-life' => ['name' => 'Sun Life', 'source' => 'local', 'image_name' => 'sun-life.png'],
      'sure-payroll' => ['name' => 'SurePayroll', 'source' => 'local', 'image_name' => 'sure-payroll.svg'],
      'symetra' => ['name' => 'Symetra', 'source' => 'local', 'image_name' => 'symetra.png'],
      'tiaa' => ['name' => 'TIAA', 'source' => 'local', 'image_name' => 'tiaa.png'],
      'the-manhattan-life-insurance-company' => ['name' => 'The Manhattan Life Insurance Company', 'source' => 'local', 'image_name' => 'the-manhattan-life-insurance-company.png'],
      'the-standard' => ['name' => 'The Standard', 'source' => 'local', 'image_name' => 'the-standard.png'],
      'thrivent-financial' => ['name' => 'Thrivent Financial', 'source' => 'local', 'image_name' => 'thrivent-financial.png'],
      'trade-gecko' => ['name' => 'Trade Gecko', 'source' => 'local', 'image_name' => 'trade-gecko.svg'],
      'transamerica' => ['name' => 'Transamerica', 'source' => 'local', 'image_name' => 'transamerica.png'],
      'turbo-tax' => ['name' => 'Turbo Tax', 'source' => 'local', 'image_name' => 'turbo-tax.svg'],
      'usaa' => ['name' => 'USAA', 'source' => 'local', 'image_name' => 'usaa.png'],
      'united-american' => ['name' => 'United American', 'source' => 'local', 'image_name' => 'united-american.png'],
      'united-home' => ['name' => 'United Home', 'source' => 'local', 'image_name' => 'united-home.png'],
      'unum' => ['name' => 'Unum', 'source' => 'local', 'image_name' => 'unum.png'],
      'vantis-life' => ['name' => 'Vantis Life', 'source' => 'local', 'image_name' => 'vantis-life.png'],
      'viasat' => ['name' => 'Viasat', 'source' => 'local', 'image_name' => 'viasat.svg', 'redb' => 'viasat-logo'],
      'vonage' => ['name' => 'Vonage', 'source' => 'local', 'image_name' => 'vonage.svg'],
      'voya-financial' => ['name' => 'Voya Financial', 'source' => 'local', 'image_name' => 'voya-financial.png'],
      'washington-national' => ['name' => 'Washington National', 'source' => 'local', 'image_name' => 'washington-national.png'],
      'wave' => ['name' => 'Wave', 'source' => 'local', 'image_name' => 'wave.svg'],
      'weebly' => ['name' => 'Weebly', 'source' => 'local', 'image_name' => 'weebly.svg'],
      'western_southern-life' => ['name' => 'Western_Southern Life', 'source' => 'local', 'image_name' => 'western_southern-life.png'],
      'wix' => ['name' => 'Wix', 'source' => 'local', 'image_name' => 'wix.svg'],
      'wordpress' => ['name' => 'WordPress', 'source' => 'local', 'image_name' => 'wordpress.svg'],
      'xero' => ['name' => 'Xero', 'source' => 'local', 'image_name' => 'xero.svg'],
      'zoho' => ['name' => 'Zoho', 'source' => 'local', 'image_name' => 'zoho.png'],
      'acorn-tv' => ['name' => 'AcornTV', 'source' => 'local', 'image_name' => 'acorn-tv.svg'],
      'amcrest' => ['name' => 'Amcrest', 'source' => 'local', 'image_name' => 'amcrest.png'],
      'august' => ['name' => 'August', 'source' => 'local', 'image_name' => 'august.svg'],
      'directv-stream' => ['name' => 'Directv Stream', 'source' => 'local', 'image_name' => 'directv-stream.svg', 'redb' => 'directv-stream-logo'],
      'expressvpn' => ['name' => 'ExpressVPN', 'source' => 'local', 'image_name' => 'expressvpn.svg'],
      'hbo-max' => ['name' => 'HBO Max', 'source' => 'local', 'image_name' => 'hbo-max.svg', 'redb' => 'hbo-max-logo'],
      'hbo' => ['name' => 'HBO', 'source' => 'local', 'image_name' => 'hbo.svg', 'redb' => 'hbo-logo'],
      'keepsolid' => ['name' => 'KeepSolid', 'source' => 'local', 'image_name' => 'keepsolid.svg'],
      'kwikset' => ['name' => 'Kwikset', 'source' => 'local', 'image_name' => 'kwikset.svg'],
      'netatmo' => ['name' => 'Netatmo', 'source' => 'local', 'image_name' => 'netatmo.svg'],
      'norton-securevpn' => ['name' => 'Norton SecureVPN', 'source' => 'local', 'image_name' => 'norton-securevpn.png'],
      'roku' => ['name' => 'Roku', 'source' => 'local', 'image_name' => 'roku.svg'],
      'samsung-smartthings-adt' => ['name' => 'Samsung Smartthings ADT', 'source' => 'local', 'image_name' => 'samsung-smartthings-adt.svg', 'redb' => 'samsung-smartthings-with-adt-logo'],
      'sengled' => ['name' => 'Sengled', 'source' => 'local', 'image_name' => 'sengled.svg'],
      'twigby' => ['name' => 'Twigby', 'source' => 'local', 'image_name' => 'twigby.png'],
      'vidgo' => ['name' => 'Vidgo', 'source' => 'local', 'image_name' => 'vidgo.svg'],
      'windscribe' => ['name' => 'Windscribe', 'source' => 'local', 'image_name' => 'windscribe.svg'],
      'xfinity-mobile' => ['name' => 'Xfinity Mobile', 'source' => 'local', 'image_name' => 'xfinity-mobile.svg'],
      'youtubetv' => ['name' => 'YouTubeTV', 'source' => 'local', 'image_name' => 'youtubetv.svg', 'redb' => 'youtube-tv-logo'],
      '10-all-access' => ['name' => '10 All Access', 'source' => 'local', 'image_name' => '10-all-access.svg'],
      'amazon' => ['name' => 'Amazon', 'source' => 'local', 'image_name' => 'amazon.svg'],
      'amazon-prime' => ['name' => 'Amazon Prime', 'source' => 'local', 'image_name' => 'amazon-prime.png', 'redb' => 'amazon-prime-logo'],
      'ebay' => ['name' => 'eBay', 'source' => 'local', 'image_name' => 'ebay.svg'],
      'freeup-mobile' => ['name' => 'FreeUp Mobile', 'source' => 'local', 'image_name' => 'freeup-mobile.svg'],
      'good-guys' => ['name' => 'Good Guys', 'source' => 'local', 'image_name' => 'good-guys.svg'],
      'grande-communications' => ['name' => 'Grande Communications', 'source' => 'local', 'image_name' => 'astound-grande.svg'],
      'h2o-wireless' => ['name' => 'H2O Wireless', 'source' => 'local', 'image_name' => 'h2o-wireless.png'],
      'harvey-norman' => ['name' => 'Harvey Norman', 'source' => 'local', 'image_name' => 'harvey-norman.png'],
      'imdb-tv' => ['name' => 'IMDB TV', 'source' => 'local', 'image_name' => 'imdb-tv.svg'],
      'nfl-sunday-ticket' => ['name' => 'NFL Sunday Ticket', 'source' => 'local', 'image_name' => 'nfl-sunday-ticket.png'],
      'rcn' => ['name' => 'Astound (formerly RCN)', 'source' => 'local', 'image_name' => 'rcn.svg'],
      'red-pocket-mobile' => ['name' => 'Red Pocket Mobile', 'source' => 'local', 'image_name' => 'red-pocket-mobile.png'],
      'remo-plus' => ['name' => 'Remo+', 'source' => 'local', 'image_name' => 'remo-plus.png'],
      'schlage' => ['name' => 'Schlage', 'source' => 'local', 'image_name' => 'schlage.png'],
      'suddenlink' => ['name' => 'SuddenLink', 'source' => 'local', 'image_name' => 'suddenlink.png', 'redb' => 'suddenlink-logo'],
      'tubi' => ['name' => 'Tubi', 'source' => 'local', 'image_name' => 'tubi.svg'],
      'vudu' => ['name' => 'Vudu', 'source' => 'local', 'image_name' => 'vudu.svg'],
      'buckeye-broadband' => ['name' => 'Buckeye Broadband', 'source' => 'local', 'image_name' => 'buckeye-broadband.svg', 'redb' => 'buckeye-logo'],
      'sparklight' => ['name' => 'Sparklight', 'source' => 'local', 'image_name' => 'sparklight.svg', 'redb' => 'sparklight-logo'],
      'kinetic-by-windstream' => ['name' => 'Kinetic by Windstream', 'source' => 'local', 'image_name' => 'kinetic-by-windstream.png', 'redb' => 'windstream-logo'],
      'cable-one' => ['name' => 'Cable One', 'source' => 'local', 'image_name' => 'cable-one.png', 'redb' => 'cable-one-logo'],
      'espn-plus' => ['name' => 'ESPN Plus', 'source' => 'local', 'image_name' => 'espn-plus.svg', 'redb' => 'espn-plus-logo'],
      'frndly-tv' => ['name' => 'Frndly TV', 'source' => 'local', 'image_name' => 'frndly-tv.png', 'redb' => 'frndly-tv-logo'],
      'fubo-tv' => ['name' => 'Fubo TV', 'source' => 'local', 'image_name' => 'fubo.svg', 'redb' => 'fubo-logo'],
      'hulu' => ['name' => 'Hulu', 'source' => 'local', 'image_name' => 'hulu.svg', 'redb' => 'hulu-logo'],
      'metronet' => ['name' => 'Metro Net', 'source' => 'local', 'image_name' => 'metronet.png', 'redb' => 'metronet-logo'],
      'philo' => ['name' => 'Philo', 'source' => 'local', 'image_name' => 'philo.svg', 'redb' => 'philo-logo'],
      'playstation-vue' => ['name' => 'Playstation Vue', 'source' => 'local', 'image_name' => 'playstation-vue.png', 'redb' => 'playstation-vue-logo'],
      'sling' => ['name' => 'Sling', 'source' => 'local', 'image_name' => 'sling.png', 'redb' => 'sling-logo'],
      'wow' => ['name' => 'Wow', 'source' => 'local', 'image_name' => 'wow.png', 'redb' => 'wow-logo'],
      'ziply-fiber' => ['name' => 'Ziply Fiber', 'source' => 'local', 'image_name' => 'ziply-fiber.png', 'redb' => 'ziply-fiber-logo'],
          ];

ksort($logos_array, SORT_STRING);

// foreach ($logos_array as $key => $val) {
//       echo ($val);
//       echo("<br>");
//   }



// array_multisort($logos_array, SORT_DESC);

foreach ($logos_array as $key1 => $value1) {
      // print_r($logo);
      echo("'" . $key1 . "'" . " => [");
      
      foreach ($value1 as $key2 => $value2){
            $lastKey = array_key_last($value1);
            $firstKey = array_key_first($value1);

            // if ($key2 ==$firstKey) {
            //       echo("");
            // }
            echo("'" . $key2 . "' => '" . $value2 . "'");            
            if ($key2 !== $lastKey){
                  echo(", ");
            }
      }
      echo("],");
      echo('<br>');
}
// print_r($logos_array);